// ============================================================
// LIVING EAMON — Spell registry (KARMA Sprint 7)
//
// 64 spells across the Eight Circles. Words of Power use the Old
// Tongue vocabulary canonically defined in SORCERY.md §5b — Latin-
// rooted, compositional ([operator] [element] with `Mag` intensifier).
// Mana costs and reagent combinations follow classic-RPG conventions
// per SORCERY.md §6.
//
// Sprint 7a wires the registry + parser + Circle-gating +
// Illumination drain. Effect dispatch is stubbed (chronicle entries
// describing what happens). Sprint 7b will implement numeric
// effects per `effectKind`.
// ============================================================

import type { Spell, Circle } from "./types";

export const SPELL_REGISTRY: Spell[] = [
  // ── Circle 1 — mana 4 ─────────────────────────────────────
  {
    id: "clumsy",
    name: "Clumsy",
    circle: 1,
    words: ["Min", "Dex"],
    manaCost: 4,
    reagents: ["blood_moss", "nightshade"],
    illuminationDrain: 0,
    effectKind: "debuff",
    description: "Heaviness gathers, ready to weight the target's limbs into stumbling slowness.",
  },
  {
    id: "create-food",
    name: "Create Food",
    circle: 1,
    words: ["Crea", "Pan"],
    manaCost: 4,
    reagents: ["garlic", "ginseng", "mandrake_root"],
    illuminationDrain: 0,
    effectKind: "utility",
    description: "The Art reaches for plain food, ready to coalesce bread and a wedge of cheese from the air.",
  },
  {
    id: "feeblemind",
    name: "Feeblemind",
    circle: 1,
    words: ["Min", "Mens"],
    manaCost: 4,
    reagents: ["ginseng", "nightshade"],
    illuminationDrain: 0,
    effectKind: "debuff",
    description: "A thickening reaches for the target's thoughts, ready to make speech an effort.",
  },
  {
    id: "heal",
    name: "Heal",
    circle: 1,
    words: ["Aug", "Vit"],
    manaCost: 4,
    reagents: ["garlic", "ginseng", "spider_silk"],
    illuminationDrain: 0,
    effectKind: "heal",
    healRoll: { min: 6, max: 12 },
    description: "A small warmth gathers under the skin, ready to close a wound a little.",
  },
  {
    id: "magic-arrow",
    name: "Magic Arrow",
    circle: 1,
    words: ["Crea", "Sag"],
    manaCost: 4,
    reagents: ["sulfurous_ash"],
    illuminationDrain: 0,
    effectKind: "damage",
    damageRoll: { min: 14, max: 18 },
    description: "Pale fire gathers at the caster's hand, ready to leap forth straight and fast.",
  },
  {
    id: "night-sight",
    name: "Night Sight",
    circle: 1,
    words: ["Aug", "Vid"],
    manaCost: 4,
    reagents: ["sulfurous_ash", "spider_silk"],
    illuminationDrain: 0,
    effectKind: "buff",
    description: "The Art reaches for your eyes, ready to loosen the dark's grip and draw shapes out of shadow.",
  },
  {
    id: "reactive-armor",
    name: "Reactive Armor",
    circle: 1,
    words: ["Dur", "Cor"],
    manaCost: 4,
    reagents: ["garlic", "sulfurous_ash", "spider_silk"],
    illuminationDrain: 0,
    effectKind: "buff",
    description: "A hardening gathers in the skin, ready to make it briefly stone-cousined and stubborn against blades.",
  },
  {
    id: "weaken",
    name: "Weaken",
    circle: 1,
    words: ["Min", "Pot"],
    manaCost: 4,
    reagents: ["garlic", "nightshade"],
    illuminationDrain: 0,
    effectKind: "debuff",
    description: "A faltering reaches for the target's grip, ready to make any held weapon feel heavier than it should.",
  },

  // ── Circle 2 — mana 6 ─────────────────────────────────────
  {
    id: "agility",
    name: "Agility",
    circle: 2,
    words: ["Aug", "Dex"],
    manaCost: 6,
    reagents: ["blood_moss", "mandrake_root"],
    illuminationDrain: 0,
    effectKind: "buff",
    description: "Quickness gathers in the limbs, ready to give them their old speed; the room would feel a half-step slower.",
  },
  {
    id: "cunning",
    name: "Cunning",
    circle: 2,
    words: ["Aug", "Mens"],
    manaCost: 6,
    reagents: ["nightshade", "mandrake_root"],
    illuminationDrain: 0,
    effectKind: "buff",
    description: "A sharpening gathers in thought, ready to draw out connections that were dark a moment ago.",
  },
  {
    id: "cure",
    name: "Cure",
    circle: 2,
    words: ["Solv", "Tox"],
    manaCost: 6,
    reagents: ["garlic", "ginseng"],
    illuminationDrain: 0,
    effectKind: "heal",
    description: "The Art reaches for the poisoned places, ready to loosen the toxin's hold and return color to the wounded.",
  },
  {
    id: "harm",
    name: "Harm",
    circle: 2,
    words: ["Min", "Vit"],
    manaCost: 6,
    reagents: ["nightshade", "spider_silk"],
    illuminationDrain: 0,
    effectKind: "damage",
    damageRoll: { min: 23, max: 29 },
    description: "A cold hand gathers, ready to close briefly on the target's heart and let go.",
  },
  {
    id: "magic-trap",
    name: "Magic Trap",
    circle: 2,
    words: ["Crea", "Ten"],
    manaCost: 6,
    reagents: ["garlic", "spider_silk", "sulfurous_ash"],
    illuminationDrain: 0,
    effectKind: "utility",
    description: "A waiting pattern gathers, ready to lay itself into the lock — patient, eager.",
  },
  {
    id: "remove-trap",
    name: "Remove Trap",
    circle: 2,
    words: ["Solv", "Ten"],
    manaCost: 6,
    reagents: ["blood_moss", "sulfurous_ash"],
    illuminationDrain: 0,
    effectKind: "utility",
    description: "The Art reaches for the waiting pattern, ready to relax and dissolve it; the latch would go harmless.",
  },
  {
    id: "protection",
    name: "Protection",
    circle: 2,
    words: ["Dur", "Aeg"],
    manaCost: 6,
    reagents: ["garlic", "ginseng", "sulfurous_ash"],
    illuminationDrain: 0,
    effectKind: "buff",
    description: "A focused calm gathers, ready to settle over the caster; distractions would slide off the mind.",
  },
  {
    id: "strength",
    name: "Strength",
    circle: 2,
    words: ["Aug", "Pot"],
    manaCost: 6,
    reagents: ["mandrake_root", "nightshade"],
    illuminationDrain: 0,
    effectKind: "buff",
    description: "Strength gathers, ready to stand the target a little taller; the world would weigh a little less on their shoulders.",
  },

  // ── Circle 3 — mana 9 ─────────────────────────────────────
  {
    id: "bless",
    name: "Bless",
    circle: 3,
    words: ["Mag", "Aug"],
    manaCost: 9,
    reagents: ["garlic", "mandrake_root"],
    illuminationDrain: 0,
    effectKind: "buff",
    description: "Three quiet warmths gather, ready to layer themselves into the body — quickness, sharpness, vigor.",
  },
  {
    id: "fireball",
    name: "Fireball",
    circle: 3,
    words: ["Mag", "Ign"],
    manaCost: 9,
    reagents: ["black_pearl"],
    illuminationDrain: 0,
    effectKind: "damage",
    damageRoll: { min: 26, max: 31 },
    description: "A globe of fire gathers at the caster's hand, ready to leave it and break loud where it strikes.",
  },
  {
    id: "magic-lock",
    name: "Magic Lock",
    circle: 3,
    words: ["Ten", "Via"],
    manaCost: 9,
    reagents: ["blood_moss", "garlic", "sulfurous_ash"],
    illuminationDrain: 0,
    effectKind: "utility",
    description: "A binding gathers in the latch, ready to make it refuse the room; no mundane key would move it.",
  },
  {
    id: "poison",
    name: "Poison",
    circle: 3,
    words: ["Crea", "Tox"],
    manaCost: 9,
    reagents: ["nightshade"],
    illuminationDrain: 0,
    effectKind: "debuff",
    description: "The Art reaches for the target's veins, ready to bloom black flowers beneath the skin that would not heal until cured.",
  },
  {
    id: "telekinesis",
    name: "Telekinesis",
    circle: 3,
    words: ["Tra", "Mat"],
    manaCost: 9,
    reagents: ["blood_moss", "mandrake_root"],
    illuminationDrain: 0,
    effectKind: "utility",
    description: "A lifting gathers around the named thing, ready to raise it of its own accord at the caster's small commanding gestures.",
  },
  {
    id: "teleport",
    name: "Teleport",
    circle: 3,
    words: ["Mut", "Via"],
    manaCost: 9,
    reagents: ["blood_moss", "mandrake_root"],
    illuminationDrain: 0,
    effectKind: "movement",
    description: "The way bends and gathers itself, ready to fade the caster from one place and resolve them where the eye looked.",
  },
  {
    id: "unlock",
    name: "Unlock",
    circle: 3,
    words: ["Lib", "Via"],
    manaCost: 9,
    reagents: ["blood_moss", "sulfurous_ash"],
    illuminationDrain: 0,
    effectKind: "utility",
    description: "The Art reaches for the lock, ready to remind it of being open.",
  },
  {
    id: "wall-of-stone",
    name: "Wall of Stone",
    circle: 3,
    words: ["Crea", "Mur"],
    manaCost: 9,
    reagents: ["blood_moss", "garlic"],
    illuminationDrain: 0,
    effectKind: "field",
    description: "Energy gathers to pull stone up from the earth in the shape of a wall.",
  },

  // ── Circle 4 — mana 11 — Illumination begins to darken ───
  {
    id: "arch-cure",
    name: "Arch Cure",
    circle: 4,
    words: ["Mag", "Solv", "Tox"],
    manaCost: 11,
    reagents: ["garlic", "ginseng", "mandrake_root"],
    illuminationDrain: -2,
    effectKind: "heal",
    description: "The Art reaches outward from the caster, ready to drive poison from the air; allies within reach would exhale together.",
  },
  {
    id: "arch-protection",
    name: "Arch Protection",
    circle: 4,
    words: ["Mag", "Dur", "Aeg"],
    manaCost: 11,
    reagents: ["garlic", "ginseng", "mandrake_root", "sulfurous_ash"],
    illuminationDrain: -2,
    effectKind: "buff",
    description: "Focused calm gathers around the caster, ready to pass to every ally near; spells would not interrupt them.",
  },
  {
    id: "curse",
    name: "Curse",
    circle: 4,
    words: ["Mag", "Min"],
    manaCost: 11,
    reagents: ["garlic", "nightshade", "sulfurous_ash"],
    illuminationDrain: -2,
    effectKind: "debuff",
    description: "Three quiet wrongs gather, ready to settle into the target's body — slowness, fog, weakness.",
  },
  {
    id: "fire-field",
    name: "Fire Field",
    circle: 4,
    words: ["Crea", "Camp", "Ign"],
    manaCost: 11,
    reagents: ["black_pearl", "spider_silk", "sulfurous_ash"],
    illuminationDrain: -2,
    effectKind: "field",
    description: "Fire gathers along the named line, ready to lift knee-high from the floor and stay where it is told.",
  },
  {
    id: "greater-heal",
    name: "Greater Heal",
    circle: 4,
    words: ["Mag", "Aug", "Vit"],
    manaCost: 11,
    reagents: ["garlic", "ginseng", "mandrake_root", "spider_silk"],
    illuminationDrain: -2,
    effectKind: "heal",
    healRoll: { min: 25, max: 40 },
    description: "A deep warmth gathers under the skin, ready to knit major wounds shut; the target would stand surprised at how easy it became.",
  },
  {
    id: "lightning",
    name: "Lightning",
    circle: 4,
    words: ["Crea", "Ful"],
    manaCost: 11,
    reagents: ["mandrake_root", "sulfurous_ash"],
    illuminationDrain: -2,
    effectKind: "damage",
    damageRoll: { min: 30, max: 34 },
    description: "A white seam gathers between caster and target, ready to split the air — gone before the thunder would arrive.",
  },
  {
    id: "mana-drain",
    name: "Mana Drain",
    circle: 4,
    words: ["Min", "Arc"],
    manaCost: 11,
    reagents: ["black_pearl", "mandrake_root", "spider_silk"],
    illuminationDrain: -2,
    effectKind: "debuff",
    description: "The Art reaches for whatever power the target has gathered, ready to slip it out of them in a long draining breath.",
  },
  {
    id: "recall",
    name: "Recall",
    circle: 4,
    words: ["Crea", "Tra", "Via"],
    manaCost: 11,
    reagents: ["black_pearl", "blood_moss", "mandrake_root"],
    illuminationDrain: -2,
    effectKind: "movement",
    description: "The room would fold; the Art reaches for a marked place, ready to set the caster elsewhere — somewhere they have stood before.",
  },

  // ── Circle 5 — mana 14 ────────────────────────────────────
  {
    id: "blade-spirits",
    name: "Blade Spirits",
    circle: 5,
    words: ["Crea", "Bes", "Fer"],
    manaCost: 14,
    reagents: ["black_pearl", "mandrake_root", "nightshade"],
    illuminationDrain: -4,
    effectKind: "summon",
    description: "Spinning blades gather from nowhere, ready to lift and hunt the caster's enemies until they are spent.",
  },
  {
    id: "dispel-field",
    name: "Dispel Field",
    circle: 5,
    words: ["Solv", "Camp"],
    manaCost: 14,
    reagents: ["black_pearl", "garlic", "spider_silk", "sulfurous_ash"],
    illuminationDrain: -4,
    effectKind: "field",
    description: "The Art reaches for a held pattern of force, ready to unwind it where the caster points.",
  },
  {
    id: "magic-reflection",
    name: "Magic Reflection",
    circle: 5,
    words: ["Mut", "Arc"],
    manaCost: 14,
    reagents: ["garlic", "mandrake_root", "spider_silk"],
    illuminationDrain: -4,
    effectKind: "buff",
    description: "A polished shell of mind gathers, ready to close over the caster; what is sent would be returned.",
  },
  {
    id: "mind-blast",
    name: "Mind Blast",
    circle: 5,
    words: ["Mag", "Ict", "Mens"],
    manaCost: 14,
    reagents: ["black_pearl", "mandrake_root", "nightshade", "sulfurous_ash"],
    illuminationDrain: -4,
    effectKind: "damage",
    damageRoll: { min: 40, max: 42 },
    description: "A cold pressure gathers in the target's thoughts, ready to crack them like ice on a pond; they would forget the next thing they were going to do.",
  },
  {
    id: "paralyze",
    name: "Paralyze",
    circle: 5,
    words: ["Ten", "Cor"],
    manaCost: 14,
    reagents: ["black_pearl", "nightshade", "spider_silk"],
    illuminationDrain: -4,
    effectKind: "debuff",
    description: "A binding gathers around the target's body, ready to make it forget motion is allowed; it would remember when something strikes them.",
  },
  {
    id: "poison-field",
    name: "Poison Field",
    circle: 5,
    words: ["Crea", "Camp", "Tox"],
    manaCost: 14,
    reagents: ["black_pearl", "nightshade", "spider_silk"],
    illuminationDrain: -4,
    effectKind: "field",
    description: "Green air gathers in a room-sized cloud, ready to settle; breathing it would have consequences.",
  },
  {
    id: "summon-creature",
    name: "Summon Creature",
    circle: 5,
    words: ["Crea", "Bes"],
    manaCost: 14,
    reagents: ["blood_moss", "mandrake_root", "spider_silk"],
    illuminationDrain: -4,
    effectKind: "summon",
    description: "The Art reaches into the further places, ready to call something that would wander in and fight while it remembers being called.",
  },

  // ── Circle 6 — mana 20 ────────────────────────────────────
  {
    id: "dispel",
    name: "Dispel",
    circle: 6,
    words: ["Solv", "Bes"],
    manaCost: 20,
    reagents: ["garlic", "mandrake_root", "sulfurous_ash"],
    illuminationDrain: -8,
    effectKind: "utility",
    description: "The Art reaches for whatever was called here, ready to send it home; it would not fight the going.",
  },
  {
    id: "energy-bolt",
    name: "Energy Bolt",
    circle: 6,
    words: ["Mag", "Ict", "Arc"],
    manaCost: 20,
    reagents: ["black_pearl", "nightshade"],
    illuminationDrain: -8,
    effectKind: "damage",
    damageRoll: { min: 51, max: 56 },
    description: "A bar of pale energy gathers, ready to cross the room; the target would be much less than they were.",
  },
  {
    id: "explosion",
    name: "Explosion",
    circle: 6,
    words: ["Mag", "Arc", "Ign"],
    manaCost: 20,
    reagents: ["blood_moss", "mandrake_root"],
    illuminationDrain: -8,
    effectKind: "damage",
    damageRoll: { min: 51, max: 56 },
    description: "A sphere of fire gathers, set on a delay of heartbeats, ready to break and change the room.",
  },
  {
    id: "invisibility",
    name: "Invisibility",
    circle: 6,
    words: ["Vel", "Cor"],
    manaCost: 20,
    reagents: ["blood_moss", "nightshade"],
    illuminationDrain: -8,
    effectKind: "conceal",
    description: "A veil gathers around the caster, ready to make the eye reach for them and find the room behind; footsteps would remain.",
  },
  {
    id: "mark",
    name: "Mark",
    circle: 6,
    words: ["Crea", "Sig", "Loc"],
    manaCost: 20,
    reagents: ["black_pearl", "blood_moss", "mandrake_root"],
    illuminationDrain: -8,
    effectKind: "utility",
    description: "The caster gathers this place's signature into a stone they carry; Recall would return them here.",
  },
  {
    id: "mass-curse",
    name: "Mass Curse",
    circle: 6,
    words: ["Mag", "Pluv", "Min"],
    manaCost: 20,
    reagents: ["garlic", "mandrake_root", "nightshade", "sulfurous_ash"],
    illuminationDrain: -8,
    effectKind: "debuff",
    description: "Slowness, fog, and weakness gather, ready to lay themselves over every enemy in the room at once.",
  },
  {
    id: "paralyze-field",
    name: "Paralyze Field",
    circle: 6,
    words: ["Crea", "Camp", "Ten"],
    manaCost: 20,
    reagents: ["black_pearl", "ginseng", "spider_silk"],
    illuminationDrain: -8,
    effectKind: "field",
    description: "A binding gathers along a line on the floor, ready to make anyone who crosses it forget that motion is allowed.",
  },
  {
    id: "reveal",
    name: "Reveal",
    circle: 6,
    words: ["Solv", "Vel"],
    manaCost: 20,
    reagents: ["blood_moss", "sulfurous_ash"],
    illuminationDrain: -8,
    effectKind: "reveal",
    description: "The Art reaches into the room's hiding-places, ready to shrug whatever lurks out of cover; the caster would see them all.",
  },

  // ── Circle 7 — mana 40 ────────────────────────────────────
  {
    id: "chain-lightning",
    name: "Chain Lightning",
    circle: 7,
    words: ["Crea", "Pluv", "Ful"],
    manaCost: 40,
    reagents: ["black_pearl", "blood_moss", "mandrake_root", "sulfurous_ash"],
    illuminationDrain: -15,
    effectKind: "damage",
    damageRoll: { min: 64, max: 69 },
    description: "Lightning gathers at the caster, ready to fall first on the named target and from there to find the others on its own.",
  },
  {
    id: "energy-field",
    name: "Energy Field",
    circle: 7,
    words: ["Crea", "Camp", "Arc"],
    manaCost: 40,
    reagents: ["black_pearl", "mandrake_root", "spider_silk", "sulfurous_ash"],
    illuminationDrain: -15,
    effectKind: "field",
    description: "Standing force gathers along the named line, ready to make a wall that would block the room as a hand blocks a doorway.",
  },
  {
    id: "flamestrike",
    name: "Flamestrike",
    circle: 7,
    words: ["Crea", "Mag", "Ign"],
    manaCost: 40,
    reagents: ["spider_silk", "sulfurous_ash"],
    illuminationDrain: -15,
    effectKind: "damage",
    damageRoll: { min: 64, max: 69 },
    description: "A column of fire gathers above the target's exact place, ready to descend; everything within it would be removed.",
  },
  {
    id: "gate-travel",
    name: "Gate Travel",
    circle: 7,
    words: ["Mag", "Mut", "Via"],
    manaCost: 40,
    reagents: ["black_pearl", "mandrake_root", "sulfurous_ash"],
    illuminationDrain: -15,
    effectKind: "movement",
    description: "An oval gathers in the air, ready to open onto the caster's marked place on its other side.",
  },
  {
    id: "mana-vampire",
    name: "Mana Vampire",
    circle: 7,
    words: ["Tra", "Arc"],
    manaCost: 40,
    reagents: ["black_pearl", "blood_moss", "mandrake_root", "spider_silk"],
    illuminationDrain: -15,
    effectKind: "debuff",
    description: "The Art reaches for the target's gathered power, ready not to lose it but to take it; the caster would be the larger for it.",
  },
  {
    id: "mass-dispel",
    name: "Mass Dispel",
    circle: 7,
    words: ["Mag", "Solv", "Bes"],
    manaCost: 40,
    reagents: ["black_pearl", "garlic", "mandrake_root", "sulfurous_ash"],
    illuminationDrain: -15,
    effectKind: "utility",
    description: "The Art reaches outward from the caster, ready to send every called creature in the room back where it came from.",
  },
  {
    id: "meteor-swarm",
    name: "Meteor Swarm",
    circle: 7,
    words: ["Crea", "Pluv", "Ign"],
    manaCost: 40,
    reagents: ["blood_moss", "mandrake_root", "spider_silk", "sulfurous_ash"],
    illuminationDrain: -15,
    effectKind: "damage",
    damageRoll: { min: 64, max: 69 },
    description: "Fire-stones gather above, ready to fall through the ceiling and find whoever they can reach.",
  },
  {
    id: "polymorph",
    name: "Polymorph",
    circle: 7,
    words: ["Mut", "Cor"],
    manaCost: 40,
    reagents: ["blood_moss", "mandrake_root", "spider_silk"],
    illuminationDrain: -15,
    effectKind: "transform",
    description: "A change gathers in the caster, ready to make them briefly something else; the going-back would take as well.",
  },

  // ── Circle 8 — mana 50 — the descent ──────────────────────
  {
    id: "earthquake",
    name: "Earthquake",
    circle: 8,
    words: ["Mag", "Ict", "Terr"],
    manaCost: 50,
    reagents: ["blood_moss", "ginseng", "mandrake_root", "sulfurous_ash"],
    illuminationDrain: -30,
    effectKind: "damage",
    damageRoll: { min: 25, max: 35 },
    description: "The Art reaches into the floor, ready to remind it of being a fault; everyone within reach would fall.",
  },
  {
    id: "energy-vortex",
    name: "Energy Vortex",
    circle: 8,
    words: ["Crea", "Bes", "Arc"],
    manaCost: 50,
    reagents: ["black_pearl", "blood_moss", "mandrake_root", "nightshade"],
    illuminationDrain: -30,
    effectKind: "summon",
    description: "A storm gathers in the room, ready to rise with a hunger turned loose, that it might hunt.",
  },
  {
    id: "resurrection",
    name: "Resurrection",
    circle: 8,
    words: ["Solv", "Mort"],
    manaCost: 50,
    reagents: ["blood_moss", "garlic", "ginseng"],
    illuminationDrain: -30,
    effectKind: "heal",
    description: "The Art reaches into the great quiet beyond the body, ready to ask a soul that had taken its leave to return; sometimes it does.",
  },
  {
    id: "summon-air-elemental",
    name: "Summon Air Elemental",
    circle: 8,
    words: ["Crea", "Bes", "Aer"],
    manaCost: 50,
    reagents: ["blood_moss", "mandrake_root", "spider_silk"],
    illuminationDrain: -30,
    effectKind: "summon",
    description: "Wind gathers from the further places, ready to enter the room as a tall moving column and accept having a name.",
  },
  {
    id: "summon-daemon",
    name: "Summon Daemon",
    circle: 8,
    words: ["Crea", "Bes", "Mort"],
    manaCost: 50,
    reagents: ["blood_moss", "mandrake_root", "spider_silk", "sulfurous_ash"],
    illuminationDrain: -30,
    effectKind: "summon",
    description: "The Art reaches into the dark places, ready to summon something that takes orders and remembers being asked.",
  },
  {
    id: "summon-earth-elemental",
    name: "Summon Earth Elemental",
    circle: 8,
    words: ["Crea", "Bes", "Terr"],
    manaCost: 50,
    reagents: ["blood_moss", "mandrake_root", "spider_silk"],
    illuminationDrain: -30,
    effectKind: "summon",
    description: "The Art reaches into the floor, ready to make it stand up and walk; it would have no opinions but the caster's.",
  },
  {
    id: "summon-fire-elemental",
    name: "Summon Fire Elemental",
    circle: 8,
    words: ["Crea", "Bes", "Ign"],
    manaCost: 50,
    reagents: ["blood_moss", "mandrake_root", "spider_silk", "sulfurous_ash"],
    illuminationDrain: -30,
    effectKind: "summon",
    description: "Fire gathers from somewhere it is more itself, ready to step in as a figure; it would be patient.",
  },
  {
    id: "summon-water-elemental",
    name: "Summon Water Elemental",
    circle: 8,
    words: ["Crea", "Bes", "Aqu"],
    manaCost: 50,
    reagents: ["blood_moss", "mandrake_root", "spider_silk"],
    illuminationDrain: -30,
    effectKind: "summon",
    description: "Water gathers, ready to rise as a tower in the rough shape of a person; it would move slowly, and not stop.",
  },
];

// ── Lookup helpers ───────────────────────────────────────────

const BY_ID: Record<string, Spell> = Object.fromEntries(
  SPELL_REGISTRY.map(s => [s.id, s])
);

/** Find a spell by its stable ID. */
export function getSpellById(id: string): Spell | null {
  return BY_ID[id] ?? null;
}

/**
 * Find a spell by its Words of Power. Tokens are matched
 * case-insensitively and order matters (the runic grammar is
 * compositional). Returns null if no spell matches the exact
 * token sequence.
 */
export function getSpellByWords(words: string[]): Spell | null {
  if (words.length === 0) return null;
  const lower = words.map(w => w.toLowerCase());
  for (const spell of SPELL_REGISTRY) {
    if (spell.words.length !== lower.length) continue;
    let ok = true;
    for (let i = 0; i < lower.length; i++) {
      if (spell.words[i].toLowerCase() !== lower[i]) {
        ok = false;
        break;
      }
    }
    if (ok) return spell;
  }
  return null;
}

/** All spells of a given circle, in registry order. */
export function getSpellsByCircle(circle: Circle): Spell[] {
  return SPELL_REGISTRY.filter(s => s.circle === circle);
}

/** Total spell count — used by tests + dump scripts. */
export function spellCount(): number {
  return SPELL_REGISTRY.length;
}
