// ============================================================
// LIVING EAMON — Spell registry (KARMA Sprint 7)
//
// 64 spells across the Eight Circles. Words of Power use the Old
// Tongue vocabulary canonically defined in SORCERY.md §5b — Latin-
// rooted, compositional ([operator] [element] with `Mag` intensifier).
// Mana costs and reagent combinations follow classic-RPG conventions
// per SORCERY.md §6.
//
// Sprint 7a wires the registry + parser + Circle-gating +
// Illumination drain. Effect dispatch is stubbed (chronicle entries
// describing what happens). Sprint 7b will implement numeric
// effects per `effectKind`.
// ============================================================

import type { Spell, Circle } from "./types";

export const SPELL_REGISTRY: Spell[] = [
  // ── Circle 1 — mana 4 ─────────────────────────────────────
  {
    id: "clumsy",
    name: "Clumsy",
    circle: 1,
    words: ["Min", "Dex"],
    manaCost: 4,
    reagents: ["blood_moss", "nightshade"],
    illuminationDrain: 0,
    effectKind: "debuff",
    description: "The target's limbs grow heavy and slow. A stumble where there should not be one.",
  },
  {
    id: "create-food",
    name: "Create Food",
    circle: 1,
    words: ["Crea", "Pan"],
    manaCost: 4,
    reagents: ["garlic", "ginseng", "mandrake_root"],
    illuminationDrain: 0,
    effectKind: "utility",
    description: "Bread and a wedge of cheese coalesce in the air, plain and edible.",
  },
  {
    id: "feeblemind",
    name: "Feeblemind",
    circle: 1,
    words: ["Min", "Mens"],
    manaCost: 4,
    reagents: ["ginseng", "nightshade"],
    illuminationDrain: 0,
    effectKind: "debuff",
    description: "The target's thoughts thicken; speech becomes effort.",
  },
  {
    id: "heal",
    name: "Heal",
    circle: 1,
    words: ["Aug", "Vit"],
    manaCost: 4,
    reagents: ["garlic", "ginseng", "spider_silk"],
    illuminationDrain: 0,
    effectKind: "heal",
    description: "A small warmth gathers under the skin; a wound closes a little.",
  },
  {
    id: "magic-arrow",
    name: "Magic Arrow",
    circle: 1,
    words: ["Crea", "Sag"],
    manaCost: 4,
    reagents: ["sulfurous_ash"],
    illuminationDrain: 0,
    effectKind: "damage",
    description: "A streak of pale fire leaps from the caster's hand, fast and straight.",
  },
  {
    id: "night-sight",
    name: "Night Sight",
    circle: 1,
    words: ["Aug", "Vid"],
    manaCost: 4,
    reagents: ["sulfurous_ash", "spider_silk"],
    illuminationDrain: 0,
    effectKind: "buff",
    description: "The dark loosens its grip on your eyes. Shapes resolve where there were none.",
  },
  {
    id: "reactive-armor",
    name: "Reactive Armor",
    circle: 1,
    words: ["Dur", "Cor"],
    manaCost: 4,
    reagents: ["garlic", "sulfurous_ash", "spider_silk"],
    illuminationDrain: 0,
    effectKind: "buff",
    description: "The skin hardens, briefly stone-cousined. Blades will find it stubborn.",
  },
  {
    id: "weaken",
    name: "Weaken",
    circle: 1,
    words: ["Min", "Pot"],
    manaCost: 4,
    reagents: ["garlic", "nightshade"],
    illuminationDrain: 0,
    effectKind: "debuff",
    description: "The target's grip falters. A held weapon feels heavier than it should.",
  },

  // ── Circle 2 — mana 6 ─────────────────────────────────────
  {
    id: "agility",
    name: "Agility",
    circle: 2,
    words: ["Aug", "Dex"],
    manaCost: 6,
    reagents: ["blood_moss", "mandrake_root"],
    illuminationDrain: 0,
    effectKind: "buff",
    description: "Limbs find their old quickness. The room feels a half-step slower.",
  },
  {
    id: "cunning",
    name: "Cunning",
    circle: 2,
    words: ["Aug", "Mens"],
    manaCost: 6,
    reagents: ["nightshade", "mandrake_root"],
    illuminationDrain: 0,
    effectKind: "buff",
    description: "Thought sharpens. Connections that were dark a moment ago lay themselves out.",
  },
  {
    id: "cure",
    name: "Cure",
    circle: 2,
    words: ["Solv", "Tox"],
    manaCost: 6,
    reagents: ["garlic", "ginseng"],
    illuminationDrain: 0,
    effectKind: "heal",
    description: "The poison loosens its hold. Color returns to the wounded.",
  },
  {
    id: "harm",
    name: "Harm",
    circle: 2,
    words: ["Min", "Vit"],
    manaCost: 6,
    reagents: ["nightshade", "spider_silk"],
    illuminationDrain: 0,
    effectKind: "damage",
    description: "A cold hand closes briefly on the target's heart and lets go.",
  },
  {
    id: "magic-trap",
    name: "Magic Trap",
    circle: 2,
    words: ["Crea", "Ten"],
    manaCost: 6,
    reagents: ["garlic", "spider_silk", "sulfurous_ash"],
    illuminationDrain: 0,
    effectKind: "utility",
    description: "A waiting pattern is laid into the lock — patient, eager.",
  },
  {
    id: "remove-trap",
    name: "Remove Trap",
    circle: 2,
    words: ["Solv", "Ten"],
    manaCost: 6,
    reagents: ["blood_moss", "sulfurous_ash"],
    illuminationDrain: 0,
    effectKind: "utility",
    description: "The waiting pattern relaxes, then dissolves. The latch is harmless.",
  },
  {
    id: "protection",
    name: "Protection",
    circle: 2,
    words: ["Dur", "Aeg"],
    manaCost: 6,
    reagents: ["garlic", "ginseng", "sulfurous_ash"],
    illuminationDrain: 0,
    effectKind: "buff",
    description: "A focused calm settles over the caster. Distractions slide off the mind.",
  },
  {
    id: "strength",
    name: "Strength",
    circle: 2,
    words: ["Aug", "Pot"],
    manaCost: 6,
    reagents: ["mandrake_root", "nightshade"],
    illuminationDrain: 0,
    effectKind: "buff",
    description: "The target stands a little taller; the world weighs a little less on their shoulders.",
  },

  // ── Circle 3 — mana 9 ─────────────────────────────────────
  {
    id: "bless",
    name: "Bless",
    circle: 3,
    words: ["Mag", "Aug"],
    manaCost: 9,
    reagents: ["garlic", "mandrake_root"],
    illuminationDrain: 0,
    effectKind: "buff",
    description: "Three quiet warmths layer themselves into the body — quickness, sharpness, vigor.",
  },
  {
    id: "fireball",
    name: "Fireball",
    circle: 3,
    words: ["Mag", "Ign"],
    manaCost: 9,
    reagents: ["black_pearl"],
    illuminationDrain: 0,
    effectKind: "damage",
    description: "A globe of fire leaves the caster's hand and breaks loud where it strikes.",
  },
  {
    id: "magic-lock",
    name: "Magic Lock",
    circle: 3,
    words: ["Ten", "Via"],
    manaCost: 9,
    reagents: ["blood_moss", "garlic", "sulfurous_ash"],
    illuminationDrain: 0,
    effectKind: "utility",
    description: "The latch refuses the room. No mundane key will move it.",
  },
  {
    id: "poison",
    name: "Poison",
    circle: 3,
    words: ["Crea", "Tox"],
    manaCost: 9,
    reagents: ["nightshade"],
    illuminationDrain: 0,
    effectKind: "debuff",
    description: "Black flowers bloom briefly under the target's skin. They will not heal until cured.",
  },
  {
    id: "telekinesis",
    name: "Telekinesis",
    circle: 3,
    words: ["Tra", "Mat"],
    manaCost: 9,
    reagents: ["blood_moss", "mandrake_root"],
    illuminationDrain: 0,
    effectKind: "utility",
    description: "A held thing lifts of its own accord and obeys the caster's small commanding gestures.",
  },
  {
    id: "teleport",
    name: "Teleport",
    circle: 3,
    words: ["Mut", "Via"],
    manaCost: 9,
    reagents: ["blood_moss", "mandrake_root"],
    illuminationDrain: 0,
    effectKind: "movement",
    description: "The room briefly contains two of the caster, one fading and one resolving where the eye looked.",
  },
  {
    id: "unlock",
    name: "Unlock",
    circle: 3,
    words: ["Lib", "Via"],
    manaCost: 9,
    reagents: ["blood_moss", "sulfurous_ash"],
    illuminationDrain: 0,
    effectKind: "utility",
    description: "The lock finds itself remembering open, and obliges.",
  },
  {
    id: "wall-of-stone",
    name: "Wall of Stone",
    circle: 3,
    words: ["Crea", "Mur"],
    manaCost: 9,
    reagents: ["blood_moss", "garlic"],
    illuminationDrain: 0,
    effectKind: "field",
    description: "Stone rises from the floor in the shape of a wall and does not ask permission.",
  },

  // ── Circle 4 — mana 11 — Illumination begins to darken ───
  {
    id: "arch-cure",
    name: "Arch Cure",
    circle: 4,
    words: ["Mag", "Solv", "Tox"],
    manaCost: 11,
    reagents: ["garlic", "ginseng", "mandrake_root"],
    illuminationDrain: -2,
    effectKind: "heal",
    description: "Poison flees the air around the caster. Allies within reach exhale together.",
  },
  {
    id: "arch-protection",
    name: "Arch Protection",
    circle: 4,
    words: ["Mag", "Dur", "Aeg"],
    manaCost: 11,
    reagents: ["garlic", "ginseng", "mandrake_root", "sulfurous_ash"],
    illuminationDrain: -2,
    effectKind: "buff",
    description: "The same focused calm passes from the caster to every ally near. Spells will not interrupt them.",
  },
  {
    id: "curse",
    name: "Curse",
    circle: 4,
    words: ["Mag", "Min"],
    manaCost: 11,
    reagents: ["garlic", "nightshade", "sulfurous_ash"],
    illuminationDrain: -2,
    effectKind: "debuff",
    description: "Three quiet wrongs settle into the target's body — slowness, fog, weakness.",
  },
  {
    id: "fire-field",
    name: "Fire Field",
    circle: 4,
    words: ["Crea", "Camp", "Ign"],
    manaCost: 11,
    reagents: ["black_pearl", "spider_silk", "sulfurous_ash"],
    illuminationDrain: -2,
    effectKind: "field",
    description: "A line of fire lifts from the floor, knee-high, and stays where it is told.",
  },
  {
    id: "greater-heal",
    name: "Greater Heal",
    circle: 4,
    words: ["Mag", "Aug", "Vit"],
    manaCost: 11,
    reagents: ["garlic", "ginseng", "mandrake_root", "spider_silk"],
    illuminationDrain: -2,
    effectKind: "heal",
    description: "Major wounds knit themselves shut. The target stands surprised at how easy it became.",
  },
  {
    id: "lightning",
    name: "Lightning",
    circle: 4,
    words: ["Crea", "Ful"],
    manaCost: 11,
    reagents: ["mandrake_root", "sulfurous_ash"],
    illuminationDrain: -2,
    effectKind: "damage",
    description: "A white seam splits the air between caster and target — gone before the thunder arrives.",
  },
  {
    id: "mana-drain",
    name: "Mana Drain",
    circle: 4,
    words: ["Min", "Arc"],
    manaCost: 11,
    reagents: ["black_pearl", "mandrake_root", "spider_silk"],
    illuminationDrain: -2,
    effectKind: "debuff",
    description: "Whatever power the target had gathered slips out of them in a long draining breath.",
  },
  {
    id: "recall",
    name: "Recall",
    circle: 4,
    words: ["Crea", "Tra", "Via"],
    manaCost: 11,
    reagents: ["black_pearl", "blood_moss", "mandrake_root"],
    illuminationDrain: -2,
    effectKind: "movement",
    description: "The room folds. The caster is elsewhere — somewhere they have stood before.",
  },

  // ── Circle 5 — mana 14 ────────────────────────────────────
  {
    id: "blade-spirits",
    name: "Blade Spirits",
    circle: 5,
    words: ["Crea", "Bes", "Fer"],
    manaCost: 14,
    reagents: ["black_pearl", "mandrake_root", "nightshade"],
    illuminationDrain: -4,
    effectKind: "summon",
    description: "Spinning blades lift from nowhere and hunt the caster's enemies until they are spent.",
  },
  {
    id: "dispel-field",
    name: "Dispel Field",
    circle: 5,
    words: ["Solv", "Camp"],
    manaCost: 14,
    reagents: ["black_pearl", "garlic", "spider_silk", "sulfurous_ash"],
    illuminationDrain: -4,
    effectKind: "field",
    description: "A held pattern of force unwinds where the caster points, and is no longer there.",
  },
  {
    id: "incognito",
    name: "Incognito",
    circle: 5,
    words: ["Mut", "Spec"],
    manaCost: 14,
    reagents: ["blood_moss", "mandrake_root", "nightshade", "sulfurous_ash"],
    illuminationDrain: -4,
    effectKind: "conceal",
    description: "Face, voice, and bearing slip into someone else's. Mirrors are confused.",
  },
  {
    id: "magic-reflection",
    name: "Magic Reflection",
    circle: 5,
    words: ["Mut", "Arc"],
    manaCost: 14,
    reagents: ["garlic", "mandrake_root", "spider_silk"],
    illuminationDrain: -4,
    effectKind: "buff",
    description: "A polished shell of mind closes over the caster. What is sent will be returned.",
  },
  {
    id: "mind-blast",
    name: "Mind Blast",
    circle: 5,
    words: ["Mag", "Ict", "Mens"],
    manaCost: 14,
    reagents: ["black_pearl", "mandrake_root", "nightshade", "sulfurous_ash"],
    illuminationDrain: -4,
    effectKind: "damage",
    description: "The target's thoughts crack like ice on a pond. They forget the next thing they were going to do.",
  },
  {
    id: "paralyze",
    name: "Paralyze",
    circle: 5,
    words: ["Ten", "Cor"],
    manaCost: 14,
    reagents: ["black_pearl", "nightshade", "spider_silk"],
    illuminationDrain: -4,
    effectKind: "debuff",
    description: "The target's body forgets that motion is allowed. It will remember when something strikes them.",
  },
  {
    id: "poison-field",
    name: "Poison Field",
    circle: 5,
    words: ["Crea", "Camp", "Tox"],
    manaCost: 14,
    reagents: ["black_pearl", "nightshade", "spider_silk"],
    illuminationDrain: -4,
    effectKind: "field",
    description: "Green air settles into a room-sized cloud. Breathing it has consequences.",
  },
  {
    id: "summon-creature",
    name: "Summon Creature",
    circle: 5,
    words: ["Crea", "Bes"],
    manaCost: 14,
    reagents: ["blood_moss", "mandrake_root", "spider_silk"],
    illuminationDrain: -4,
    effectKind: "summon",
    description: "Something wandered in and accepted being called. It will fight while it remembers being called.",
  },

  // ── Circle 6 — mana 20 ────────────────────────────────────
  {
    id: "dispel",
    name: "Dispel",
    circle: 6,
    words: ["Solv", "Bes"],
    manaCost: 20,
    reagents: ["garlic", "mandrake_root", "sulfurous_ash"],
    illuminationDrain: -8,
    effectKind: "utility",
    description: "Whatever was called here, the caster sends home. It does not fight the going.",
  },
  {
    id: "energy-bolt",
    name: "Energy Bolt",
    circle: 6,
    words: ["Mag", "Ict", "Arc"],
    manaCost: 20,
    reagents: ["black_pearl", "nightshade"],
    illuminationDrain: -8,
    effectKind: "damage",
    description: "A bar of pale energy crosses the room and the target is much less than they were.",
  },
  {
    id: "explosion",
    name: "Explosion",
    circle: 6,
    words: ["Mag", "Arc", "Ign"],
    manaCost: 20,
    reagents: ["blood_moss", "mandrake_root"],
    illuminationDrain: -8,
    effectKind: "damage",
    description: "A delayed sphere of fire — counted in heartbeats — and then the room is changed.",
  },
  {
    id: "invisibility",
    name: "Invisibility",
    circle: 6,
    words: ["Vel", "Cor"],
    manaCost: 20,
    reagents: ["blood_moss", "nightshade"],
    illuminationDrain: -8,
    effectKind: "conceal",
    description: "The eye reaches for the caster and finds the room behind them. Footsteps remain.",
  },
  {
    id: "mark",
    name: "Mark",
    circle: 6,
    words: ["Crea", "Sig", "Loc"],
    manaCost: 20,
    reagents: ["black_pearl", "blood_moss", "mandrake_root"],
    illuminationDrain: -8,
    effectKind: "utility",
    description: "The caster fixes this place in a stone they carry. Recall will return them here.",
  },
  {
    id: "mass-curse",
    name: "Mass Curse",
    circle: 6,
    words: ["Mag", "Pluv", "Min"],
    manaCost: 20,
    reagents: ["garlic", "mandrake_root", "nightshade", "sulfurous_ash"],
    illuminationDrain: -8,
    effectKind: "debuff",
    description: "Slowness and fog and weakness lay themselves over every enemy in the room at once.",
  },
  {
    id: "paralyze-field",
    name: "Paralyze Field",
    circle: 6,
    words: ["Crea", "Camp", "Ten"],
    manaCost: 20,
    reagents: ["black_pearl", "ginseng", "spider_silk"],
    illuminationDrain: -8,
    effectKind: "field",
    description: "A line is drawn on the floor. Anyone who crosses it forgets that motion is allowed.",
  },
  {
    id: "reveal",
    name: "Reveal",
    circle: 6,
    words: ["Solv", "Vel"],
    manaCost: 20,
    reagents: ["blood_moss", "sulfurous_ash"],
    illuminationDrain: -8,
    effectKind: "reveal",
    description: "Whatever has been hiding in the room shrugs off its hiding. The caster sees them all.",
  },

  // ── Circle 7 — mana 40 ────────────────────────────────────
  {
    id: "chain-lightning",
    name: "Chain Lightning",
    circle: 7,
    words: ["Crea", "Pluv", "Ful"],
    manaCost: 40,
    reagents: ["black_pearl", "blood_moss", "mandrake_root", "sulfurous_ash"],
    illuminationDrain: -15,
    effectKind: "damage",
    description: "The first target is the one named. The lightning, having begun, finds the others on its own.",
  },
  {
    id: "energy-field",
    name: "Energy Field",
    circle: 7,
    words: ["Crea", "Camp", "Arc"],
    manaCost: 40,
    reagents: ["black_pearl", "mandrake_root", "spider_silk", "sulfurous_ash"],
    illuminationDrain: -15,
    effectKind: "field",
    description: "A wall of standing force. It blocks the room as a hand blocks a doorway.",
  },
  {
    id: "flamestrike",
    name: "Flamestrike",
    circle: 7,
    words: ["Crea", "Mag", "Ign"],
    manaCost: 40,
    reagents: ["spider_silk", "sulfurous_ash"],
    illuminationDrain: -15,
    effectKind: "damage",
    description: "A column of fire descends on the target's exact place. Everything within it is removed.",
  },
  {
    id: "gate-travel",
    name: "Gate Travel",
    circle: 7,
    words: ["Mag", "Mut", "Via"],
    manaCost: 40,
    reagents: ["black_pearl", "mandrake_root", "sulfurous_ash"],
    illuminationDrain: -15,
    effectKind: "movement",
    description: "An oval opens in the air and the caster's marked place is on the other side of it.",
  },
  {
    id: "mana-vampire",
    name: "Mana Vampire",
    circle: 7,
    words: ["Tra", "Arc"],
    manaCost: 40,
    reagents: ["black_pearl", "blood_moss", "mandrake_root", "spider_silk"],
    illuminationDrain: -15,
    effectKind: "debuff",
    description: "The target's gathered power is not lost — it is taken. The caster is the larger for it.",
  },
  {
    id: "mass-dispel",
    name: "Mass Dispel",
    circle: 7,
    words: ["Mag", "Solv", "Bes"],
    manaCost: 40,
    reagents: ["black_pearl", "garlic", "mandrake_root", "sulfurous_ash"],
    illuminationDrain: -15,
    effectKind: "utility",
    description: "Every called creature in the room is sent back where it came from. They go.",
  },
  {
    id: "meteor-swarm",
    name: "Meteor Swarm",
    circle: 7,
    words: ["Crea", "Pluv", "Ign"],
    manaCost: 40,
    reagents: ["blood_moss", "mandrake_root", "spider_silk", "sulfurous_ash"],
    illuminationDrain: -15,
    effectKind: "damage",
    description: "A flight of fire-stones falls through the ceiling and finds whoever it can reach.",
  },
  {
    id: "polymorph",
    name: "Polymorph",
    circle: 7,
    words: ["Mut", "Cor"],
    manaCost: 40,
    reagents: ["blood_moss", "mandrake_root", "spider_silk"],
    illuminationDrain: -15,
    effectKind: "transform",
    description: "The caster is briefly something else. The change takes; the going-back does, too.",
  },

  // ── Circle 8 — mana 50 — the descent ──────────────────────
  {
    id: "earthquake",
    name: "Earthquake",
    circle: 8,
    words: ["Mag", "Ict", "Terr"],
    manaCost: 50,
    reagents: ["blood_moss", "ginseng", "mandrake_root", "sulfurous_ash"],
    illuminationDrain: -30,
    effectKind: "damage",
    description: "The floor remembers being a fault and is honest about it. Everyone falls.",
  },
  {
    id: "energy-vortex",
    name: "Energy Vortex",
    circle: 8,
    words: ["Crea", "Bes", "Arc"],
    manaCost: 50,
    reagents: ["black_pearl", "blood_moss", "mandrake_root", "nightshade"],
    illuminationDrain: -30,
    effectKind: "summon",
    description: "A storm rises in the room, given a hunger and turned loose. It hunts.",
  },
  {
    id: "resurrection",
    name: "Resurrection",
    circle: 8,
    words: ["Solv", "Mort"],
    manaCost: 50,
    reagents: ["blood_moss", "garlic", "ginseng"],
    illuminationDrain: -30,
    effectKind: "heal",
    description: "A soul that had taken its leave is asked to return. Sometimes it does.",
  },
  {
    id: "summon-air-elemental",
    name: "Summon Air Elemental",
    circle: 8,
    words: ["Crea", "Bes", "Aer"],
    manaCost: 50,
    reagents: ["blood_moss", "mandrake_root", "spider_silk"],
    illuminationDrain: -30,
    effectKind: "summon",
    description: "A tall column of moving wind enters the room and accepts having a name.",
  },
  {
    id: "summon-daemon",
    name: "Summon Daemon",
    circle: 8,
    words: ["Crea", "Bes", "Mort"],
    manaCost: 50,
    reagents: ["blood_moss", "mandrake_root", "spider_silk", "sulfurous_ash"],
    illuminationDrain: -30,
    effectKind: "summon",
    description: "Something arrives that did not arrive. It takes orders. It remembers being asked.",
  },
  {
    id: "summon-earth-elemental",
    name: "Summon Earth Elemental",
    circle: 8,
    words: ["Crea", "Bes", "Terr"],
    manaCost: 50,
    reagents: ["blood_moss", "mandrake_root", "spider_silk"],
    illuminationDrain: -30,
    effectKind: "summon",
    description: "The floor stands up and walks. It has no opinions but the caster's.",
  },
  {
    id: "summon-fire-elemental",
    name: "Summon Fire Elemental",
    circle: 8,
    words: ["Crea", "Bes", "Ign"],
    manaCost: 50,
    reagents: ["blood_moss", "mandrake_root", "spider_silk", "sulfurous_ash"],
    illuminationDrain: -30,
    effectKind: "summon",
    description: "A figure of fire steps in from somewhere fire is more itself. It is patient.",
  },
  {
    id: "summon-water-elemental",
    name: "Summon Water Elemental",
    circle: 8,
    words: ["Crea", "Bes", "Aqu"],
    manaCost: 50,
    reagents: ["blood_moss", "mandrake_root", "spider_silk"],
    illuminationDrain: -30,
    effectKind: "summon",
    description: "A tower of water in the rough shape of a person. It moves slowly. It does not stop.",
  },
];

// ── Lookup helpers ───────────────────────────────────────────

const BY_ID: Record<string, Spell> = Object.fromEntries(
  SPELL_REGISTRY.map(s => [s.id, s])
);

/** Find a spell by its stable ID. */
export function getSpellById(id: string): Spell | null {
  return BY_ID[id] ?? null;
}

/**
 * Find a spell by its Words of Power. Tokens are matched
 * case-insensitively and order matters (the runic grammar is
 * compositional). Returns null if no spell matches the exact
 * token sequence.
 */
export function getSpellByWords(words: string[]): Spell | null {
  if (words.length === 0) return null;
  const lower = words.map(w => w.toLowerCase());
  for (const spell of SPELL_REGISTRY) {
    if (spell.words.length !== lower.length) continue;
    let ok = true;
    for (let i = 0; i < lower.length; i++) {
      if (spell.words[i].toLowerCase() !== lower[i]) {
        ok = false;
        break;
      }
    }
    if (ok) return spell;
  }
  return null;
}

/** All spells of a given circle, in registry order. */
export function getSpellsByCircle(circle: Circle): Spell[] {
  return SPELL_REGISTRY.filter(s => s.circle === circle);
}

/** Total spell count — used by tests + dump scripts. */
export function spellCount(): number {
  return SPELL_REGISTRY.length;
}
