'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import sprintRegistry from '@/docs/sprint-registry.json';

// ── Generated sprint registry ─────────────────────────────────
// Sprint statuses, ship dates, and per-tool sprint lists come from
// docs/sprint-registry.json which is generated by
// scripts/build-sprint-registry.ts from the `sprints:` frontmatter
// in each docs/plans/*.md file. Editing a plan file's frontmatter
// → next docs:build → this dashboard reflects the new state.
//
// To add a new sprint: append a row in the plan file's `sprints:`
// list. To flip a sprint to shipped: change its `status` there.
// Do NOT hand-edit this dashboard's sprint data.

type SprintStatus = 'planned' | 'in-progress' | 'shipped' | 'deferred';

interface RegistrySprint {
  id: string;
  name: string;
  status: SprintStatus;
  planSlug: string;
  anchor: string;
  shipped_at?: string;
  commit?: string;
  tool?: string;
}

interface SprintRegistryShape {
  generated_at: string;
  counts: {
    total: number;
    shipped: number;
    inProgress: number;
    planned: number;
    deferred: number;
  };
  sprints: RegistrySprint[];
  by_tool: Record<string, RegistrySprint[]>;
}

const SPRINTS = sprintRegistry as unknown as SprintRegistryShape;

// ── Per-tool dashboard metadata ───────────────────────────────
// Hand-maintained: tool description, pendingTasks, featuresToCode.
// Plan-derived: status rollup + sprint list. Set `planTool` to the
// href that the plan file declares for this tool's sprints. When
// planTool is set, the dashboard pulls the sprint list from the
// registry and auto-rolls-up the status; the hand-set `status`
// field is ignored.

interface Tool {
  href: string;
  name: string;
  description: string;
  /** Hand-set status. Ignored when `planTool` resolves to ≥1 sprint. */
  status: 'live' | 'partial' | 'planned';
  /**
   * If set, treat this href as the canonical "tool" key for the
   * plan-registry rollup. Defaults to `href` — kept as a separate
   * field in case a tool's sprints live under a different key.
   */
  planTool?: string;
  pendingTasks: string[];
  /** Free-form feature ideas not yet captured as plan-tracked sprints. */
  featuresToCode: string[];
}

const TOOLS: Tool[] = [
  {
    href: '/creator-forge',
    name: 'Creator Forge',
    description:
      'Author adventure modules end-to-end: rooms, atoms, NPCs, henchmen, art, Howard-voice prose, Eamon-style maps. Open to creator + admin roles.',
    status: 'partial',
    pendingTasks: [],
    featuresToCode: [],
  },
  {
    href: '/admin/quest-lines',
    name: 'Quest Line Orchestrator',
    description:
      'Stitch Modules into multi-stage Quest Lines with opening prose, interlude atoms, persistent flags, meta-reward.',
    status: 'planned',
    pendingTasks: [],
    featuresToCode: [
      'Module spine drag-reorder + interlude atom insertion',
      'Opening + closing prose (Opus-generated, hand-edited)',
      'Zoomed-out Quest Line map',
      'Persistent flag wiring + module-completion triggers',
      'Meta-reward editor (PICSSI delta, items, legacy chronicle, Mithras Word boost)',
    ],
  },
  {
    href: '/admin/destination-review',
    name: 'Destination Room Review',
    description:
      '25 destination scenes + NPCs. Review, approve, reject, regenerate.',
    status: 'partial',
    pendingTasks: ['25 destination scenes awaiting review (bg-v3.jpg batch)'],
    featuresToCode: [
      'Wire Regenerate button to forge scripts with custom prompt',
      'Server-side persistence of approval decisions (currently localStorage only)',
      'Batch approve/reject',
      'Filter list by status (pending / approved / rejected)',
      'Promote bg-v3.jpg → bg.jpg on approval (mark primary)',
    ],
  },
  {
    href: '/admin/room-map',
    name: 'Room Map',
    description: 'Mermaid diagram of room connectivity across adventures.',
    status: 'live',
    pendingTasks: [],
    featuresToCode: [
      'Click-through navigation to room files',
      'Filter by adventure / zone',
    ],
  },
  {
    href: '/dev/sprite-review',
    name: 'Sprite Review',
    description: 'NPC/hero sprite library QA — approve, reject, touchup.',
    status: 'live',
    pendingTasks: ['Pending sprite QA queue (count TBD — read from sprite-list API)'],
    featuresToCode: [
      'Volunteer-QA workflow (third tier alongside LLM-vision + paid Turk)',
      'Trap-question reputation system',
    ],
  },
  {
    href: '/dev/sprite-touchup',
    name: 'Sprite Touchup',
    description: 'Re-roll or touch-up individual sprite candidates.',
    status: 'live',
    pendingTasks: [],
    featuresToCode: ['Bulk regenerate by tag'],
  },
  {
    href: '/admin/audio-review',
    name: 'Audio Review',
    description:
      'Eve voice (xAI TTS) narration audio — approve / reject / regen generated mp3s. Only approved audio reaches the player Reader Panel.',
    status: 'live',
    pendingTasks: [],
    featuresToCode: [
      'Bulk approve',
      'Filter by status',
      'Listen-side waveform / scrub UI',
      'Per-Howard-anchor tone-preset overrides',
    ],
  },
  {
    href: '/dev/reader-demo',
    name: 'Reader Demo',
    description:
      'End-to-end test of the Reader Panel: paste prose, generate Eve audio, approve, preview as player.',
    status: 'live',
    pendingTasks: [],
    featuresToCode: [],
  },
  {
    href: '/forge-avatar',
    name: 'Forge Avatar',
    description: 'Hero/avatar creation wizard.',
    status: 'live',
    pendingTasks: [],
    featuresToCode: [
      'Wire Stripe payment gate before character creation',
      'Per-player face variation forge (deferred until multiplayer)',
    ],
  },
];

/** Sprints declared in the registry that point at this tool's href. */
function sprintsForTool(tool: Tool): RegistrySprint[] {
  const key = tool.planTool ?? tool.href;
  return SPRINTS.by_tool[key] ?? [];
}

/**
 * Derived tool status: if the registry has sprints for this tool,
 * roll up from them; otherwise fall back to the hand-set status.
 */
function effectiveStatus(tool: Tool): Tool['status'] {
  const sprints = sprintsForTool(tool);
  if (sprints.length === 0) return tool.status;
  const shipped = sprints.filter((s) => s.status === 'shipped').length;
  if (shipped === sprints.length) return 'live';
  if (shipped > 0) return 'partial';
  return 'planned';
}

/** Plan slug for this tool's sprints, if any. Used to link to /library/plans. */
function planSlugForTool(tool: Tool): string | null {
  const sprints = sprintsForTool(tool);
  return sprints[0]?.planSlug ?? null;
}

function statusBadge(status: Tool['status']) {
  switch (status) {
    case 'live':
      return { label: 'LIVE', className: 'bg-green-600 text-white' };
    case 'partial':
      return { label: 'PARTIAL', className: 'bg-yellow-500 text-slate-900' };
    case 'planned':
      return { label: 'PLANNED', className: 'bg-slate-600 text-white' };
  }
}

function sprintPill(status: SprintStatus) {
  switch (status) {
    case 'shipped':
      return { label: 'SHIPPED', className: 'bg-green-700 text-green-100' };
    case 'in-progress':
      return { label: 'IN PROGRESS', className: 'bg-yellow-600 text-yellow-50' };
    case 'planned':
      return { label: 'PLANNED', className: 'bg-slate-700 text-slate-300' };
    case 'deferred':
      return { label: 'DEFERRED', className: 'bg-slate-800 text-slate-400 border border-slate-600' };
  }
}

interface DestinationStatus {
  id: string;
  bgStatus: 'pending' | 'approved' | 'rejected';
  npcStatus: 'pending' | 'approved' | 'rejected';
}

export default function AdminDashboard() {
  const [destinationCounts, setDestinationCounts] = useState<{
    pending: number;
    approved: number;
    rejected: number;
    total: number;
  }>({ pending: 25, approved: 0, rejected: 0, total: 25 });

  useEffect(() => {
    try {
      const raw = localStorage.getItem('destination-review-statuses');
      if (!raw) return;
      const parsed = JSON.parse(raw) as DestinationStatus[];
      let approved = 0;
      let rejected = 0;
      for (const s of parsed) {
        if (s.bgStatus === 'approved') approved++;
        else if (s.bgStatus === 'rejected') rejected++;
      }
      const total = 25;
      setDestinationCounts({
        pending: total - approved - rejected,
        approved,
        rejected,
        total,
      });
    } catch {
      // ignore corrupt storage
    }
  }, []);

  const totalFeatures = TOOLS.reduce(
    (sum, t) => sum + t.featuresToCode.length + sprintsForTool(t).length,
    0,
  );

  return (
    <div className="min-h-screen bg-slate-900 p-8">
      <div className="max-w-6xl mx-auto">
        <header className="mb-8">
          <h1 className="text-5xl font-bold text-white mb-2">Living Eamon — Admin</h1>
          <p className="text-slate-400 text-lg">
            Internal tools for content authoring, art review, and world-building.
          </p>
        </header>

        <nav className="mb-10 bg-slate-800 rounded-lg p-4 border border-slate-700">
          <h2 className="text-xs font-bold text-slate-400 uppercase tracking-wide mb-3">
            Open a tool
          </h2>
          <div className="flex flex-wrap gap-2">
            {TOOLS.map((tool) => {
              const badge = statusBadge(effectiveStatus(tool));
              return (
                <Link
                  key={tool.href}
                  href={tool.href}
                  className="group inline-flex items-center gap-2 px-3 py-1.5 bg-slate-900 hover:bg-blue-900 text-slate-200 hover:text-white text-sm rounded border border-slate-700 hover:border-blue-700 transition-colors"
                >
                  <span>{tool.name}</span>
                  <span
                    className={`text-[10px] font-bold uppercase tracking-wide px-1.5 py-0.5 rounded ${badge.className}`}
                  >
                    {badge.label}
                  </span>
                </Link>
              );
            })}
          </div>
        </nav>

        <section className="mb-10 bg-slate-800 rounded-lg p-6 border border-slate-700">
          <h2 className="text-2xl font-bold text-white mb-4">At a glance</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-slate-900 rounded p-4">
              <div className="text-slate-400 text-sm">Destination scenes</div>
              <div className="text-white text-2xl font-bold mt-1">{destinationCounts.total}</div>
              <div className="text-slate-500 text-xs mt-2">
                <span className="text-yellow-400">{destinationCounts.pending} pending</span>
                {' · '}
                <span className="text-green-400">{destinationCounts.approved} approved</span>
                {' · '}
                <span className="text-red-400">{destinationCounts.rejected} rejected</span>
              </div>
            </div>
            <div className="bg-slate-900 rounded p-4">
              <div className="text-slate-400 text-sm">Tools live</div>
              <div className="text-white text-2xl font-bold mt-1">
                {TOOLS.filter((t) => effectiveStatus(t) === 'live').length}
              </div>
            </div>
            <div className="bg-slate-900 rounded p-4">
              <div className="text-slate-400 text-sm">Tools partial</div>
              <div className="text-white text-2xl font-bold mt-1">
                {TOOLS.filter((t) => effectiveStatus(t) === 'partial').length}
              </div>
            </div>
            <div className="bg-slate-900 rounded p-4">
              <div className="text-slate-400 text-sm">Planned sprints + features</div>
              <div className="text-white text-2xl font-bold mt-1">{totalFeatures}</div>
              <div className="text-slate-500 text-xs mt-2">
                <span className="text-green-400">{SPRINTS.counts.shipped} shipped</span>
                {' · '}
                <span className="text-yellow-400">{SPRINTS.counts.inProgress} in-progress</span>
                {' · '}
                <span className="text-slate-400">{SPRINTS.counts.planned} planned</span>
              </div>
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">Tools</h2>
          <div className="grid gap-4">
            {TOOLS.map((tool) => {
              const sprints = sprintsForTool(tool);
              const badge = statusBadge(effectiveStatus(tool));
              const planSlug = planSlugForTool(tool);
              return (
                <div
                  key={tool.href}
                  className="bg-slate-800 rounded-lg p-6 border border-slate-700"
                >
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <Link
                        href={tool.href}
                        className="text-2xl font-bold text-white hover:text-blue-400"
                      >
                        {tool.name} →
                      </Link>
                      <p className="text-slate-400 mt-1">{tool.description}</p>
                      <div className="flex items-center gap-3 mt-1 text-xs">
                        <code className="text-slate-500">{tool.href}</code>
                        {planSlug && (
                          <Link
                            href={`/library/plans/${planSlug}`}
                            className="text-blue-400 hover:text-blue-300 underline decoration-dotted"
                          >
                            view plan
                          </Link>
                        )}
                      </div>
                    </div>
                    <span
                      className={`text-xs font-bold uppercase tracking-wide px-3 py-1 rounded ${badge.className}`}
                    >
                      {badge.label}
                    </span>
                  </div>

                  {tool.pendingTasks.length > 0 && (
                    <div className="mt-4">
                      <h3 className="text-sm font-bold text-yellow-400 uppercase tracking-wide mb-2">
                        Tasks awaiting
                      </h3>
                      <ul className="list-disc list-inside text-slate-300 text-sm space-y-1">
                        {tool.pendingTasks.map((task) => (
                          <li key={task}>{task}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {sprints.length > 0 && (
                    <div className="mt-4">
                      <h3 className="text-sm font-bold text-blue-400 uppercase tracking-wide mb-2">
                        Sprints (from plan)
                      </h3>
                      <ul className="space-y-1.5">
                        {sprints.map((sprint) => {
                          const pill = sprintPill(sprint.status);
                          return (
                            <li key={sprint.id} className="flex items-start gap-2 text-sm">
                              <span
                                className={`shrink-0 mt-0.5 text-[10px] font-bold uppercase tracking-wide px-2 py-0.5 rounded ${pill.className}`}
                                title={`Sprint status: ${sprint.status}${
                                  sprint.shipped_at ? ` · shipped ${sprint.shipped_at}` : ''
                                }${sprint.commit ? ` · ${sprint.commit}` : ''}`}
                              >
                                {pill.label}
                              </span>
                              <Link
                                href={`/library/plans/${sprint.planSlug}#${sprint.anchor}`}
                                className="text-slate-200 hover:text-blue-300"
                              >
                                <span className="font-mono text-blue-400 mr-1">
                                  {sprint.id.toUpperCase()}:
                                </span>
                                <span className="underline decoration-slate-600 decoration-dotted hover:decoration-blue-400">
                                  {sprint.name}
                                </span>
                                {sprint.shipped_at && (
                                  <span className="ml-2 text-[10px] text-slate-500">
                                    · {sprint.shipped_at}
                                  </span>
                                )}
                              </Link>
                            </li>
                          );
                        })}
                      </ul>
                    </div>
                  )}

                  {tool.featuresToCode.length > 0 && (
                    <div className="mt-4">
                      <h3 className="text-sm font-bold text-blue-400 uppercase tracking-wide mb-2">
                        Features to code
                      </h3>
                      <ul className="list-disc list-inside text-slate-300 text-sm space-y-1">
                        {tool.featuresToCode.map((feature) => (
                          <li key={feature}>{feature}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </section>

        <footer className="mt-10 text-slate-500 text-sm">
          Sprint statuses come from the <code>sprints:</code> frontmatter in{' '}
          <code>docs/plans/*.md</code> via{' '}
          <code>scripts/build-sprint-registry.ts</code>. To flip a sprint to
          shipped: edit the plan file and run <code>npm run docs:build</code>{' '}
          (or rely on <code>docs:watch</code>). Tool descriptions +
          features-to-code lists are hand-maintained in{' '}
          <code>app/admin/page.tsx</code>. Plans are browsable via{' '}
          <Link href="/library/plans" className="text-blue-400 hover:text-blue-300">/library/plans</Link>.
          Registry snapshot timestamp:{' '}
          <code className="text-slate-400">{SPRINTS.generated_at}</code>.
        </footer>
      </div>
    </div>
  );
}
