// ============================================================
// DESTINATION STUB ROOMS — S4d
// Minimal arrival rooms for every travel node that doesn't
// yet have a full adventure module. Players arrive here after
// long travel; they can open the MAP to travel elsewhere.
// Each room will be replaced when the relevant module ships.
// ============================================================

import { AdventureModule } from "../roomTypes";

const STUB_EMPTY = { stateModifiers: {}, npcs: [], items: [] };

export const DESTINATION_STUBS: AdventureModule = {
  id: "destination_stubs",
  name: "Destination Arrival Stubs",
  description: "Stub arrival rooms for all travel nodes pending full adventure modules.",
  entryRoom: "arrive_city_stagus",
  rooms: {
    arrive_city_vanara: {
      id: "arrive_city_vanara",
      name: "Vanara — Western Gate",
      description: "Vanara's western gate stands before you, built of pale limestone hauled from the coastal quarries. The city stretches inward, smelling of salt fish and fresh mortar. The road you walked in on connects directly to the main thoroughfare. Guild agents operate out of Vanara, though no formal hall has been established here.",
      look: "The western gate of Vanara. Limestone walls, a smell of salt from the coast, and the steady noise of a working city.",
      glance: "Vanara's western gate.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "civilized",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_city_kamula: {
      id: "arrive_city_kamula",
      name: "Kamula — Road's End",
      description: "Kamula sits in a shallow valley of fruit orchards and tile-roofed houses. The road enters through a low stone arch marked with the sigil of the Valusian road surveyors. To the north, the hills rise toward the Mirror country — the reason most travelers pass through Kamula at all.",
      look: "The entry arch of Kamula. Orchards on both sides, hills beyond. The Mirror country lies north.",
      glance: "Kamula's road-entry arch.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "civilized",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_city_talunia: {
      id: "arrive_city_talunia",
      name: "Talunia — Iron Quay",
      description: "Talunia's iron quay runs along the river for half a mile, piled with Grondar ore and finished ironwork waiting for westbound barges. The smell is metal and mud. The city rises behind the quay in tight-packed stone buildings, streets too narrow for carts. Talunia is loud, busy, and indifferent to strangers.",
      look: "Talunia's iron quay. Grondar ore piled to the waterline. Stone buildings rising behind.",
      glance: "Talunia's iron quay.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "civilized",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_city_blaal: {
      id: "arrive_city_blaal",
      name: "Blaal — River Ferry Landing",
      description: "Blaal's river ferry landing smells of river mud and tarred rope. The city is built on two levels — the lower dockside and the upper town behind a retaining wall. Blaal is the last real settlement before the road south deteriorates into game trails and rumor. Most travelers who arrive here are either heading south or very lost.",
      look: "Blaal's ferry landing. River mud, tarred rope, and a city built on two levels. The south road begins here.",
      glance: "Blaal's river ferry landing.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "civilized",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_city_stagus: {
      id: "arrive_city_stagus",
      name: "Stagus — River Gate",
      description: "Stagus huddles against the broad brown river, a frontier city of raw timber and mud-brick that smells of sawdust and river fish. The road from the west enters through a gate of undressed logs. Everything past this gate was built by people who expected the worst and planned for it. The river beyond carries nothing but drift logs and the occasional flat-bottomed scout canoe.",
      look: "Stagus's log gate. A frontier city of timber and mud-brick. The river flows brown and wide beyond.",
      glance: "Stagus's river gate.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_poi_skull_of_silence: {
      id: "arrive_poi_skull_of_silence",
      name: "Skull of Silence — Approach",
      description: "The black-stone castle called the Skull of Silence rises from the mountain ridge against a sky that seems permanently overcast. The silence that gives it its name is not peaceful — it is the silence of things that have ceased. The road ends at a ring of standing stones a quarter-mile from the gate. No sound comes from within the walls.",
      look: "The Skull of Silence, black stone on a gray ridge. Standing stones ring the approach. Total silence.",
      glance: "The Skull of Silence approach.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "night",
    },
    arrive_poi_lake_of_visions: {
      id: "arrive_poi_lake_of_visions",
      name: "Lake of Visions — Shore",
      description: "The Lake of Visions fills a broad depression in the forest, its water an unnatural blue that deepens rather than lightens in sunlight. The shore is soft black sand. No fish. No birds on the water. The oracle who dwells here speaks only to those who have survived something the lake considers worthy of note.",
      look: "The Lake of Visions. Unnatural blue water, black sand shore. No wildlife. The oracle is somewhere within.",
      glance: "The Lake of Visions shore.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_poi_accursed_gardens: {
      id: "arrive_poi_accursed_gardens",
      name: "Accursed Gardens — Entrance",
      description: "The estate gates stand open, rusted beyond closing. What was once a noble garden has been overtaken by vegetation that grows in colors not found in nature — deep purples, whites that seem to generate their own light, red-black blooms that turn toward you as you pass. The curse here is old. Whatever cursed it did a thorough job.",
      look: "The Accursed Gardens. Overgrown with wrong-colored vegetation. The gates are rusted open and cannot close.",
      glance: "The Accursed Gardens entrance.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_poi_forbidden_lake: {
      id: "arrive_poi_forbidden_lake",
      name: "Forbidden Lake — Shore",
      description: "The Forbidden Lake sits at the Valusia-Farsun border, a black mirror of water that Farsunians will not name or approach. The shore is ringed with old carved stones, their inscriptions worn smooth. Whatever the Farsunians know about this lake, they have chosen not to share it with the wider world.",
      look: "The Forbidden Lake. Black water, carved stones around the shore, and a silence Farsunians will not break.",
      glance: "The Forbidden Lake shore.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_poi_tiger_valley: {
      id: "arrive_poi_tiger_valley",
      name: "Tiger Valley — Entry",
      description: "Tiger Valley drops away from the Atlantean plateau in a series of forested terraces. The name is earned. Huge cat prints press the soft earth at the trail's edge. Hunting here is possible; being hunted is more likely. The valley is beautiful in the way that things that want to kill you often are.",
      look: "Tiger Valley. Forested terraces dropping toward the valley floor. Large cat prints in the soft earth.",
      glance: "Tiger Valley entry.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_nation_thule: {
      id: "arrive_nation_thule",
      name: "Thule — Sea Road",
      description: "Thule's sea road enters the kingdom through a carved stone arch older than the current dynasty. Gray-eyed, broad-shouldered people watch you from the doorways of longhouses. Thule is not hostile to outsiders, exactly — it is indifferent to them, which is sometimes worse. The sea is close. You can hear it.",
      look: "The Thule sea road. An ancient carved arch, longhouses, gray-eyed watchers. The sea audible beyond.",
      glance: "Thule's sea road entry.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "civilized",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_nation_commoria: {
      id: "arrive_nation_commoria",
      name: "Commoria — Mountain Pass",
      description: "Commoria's approach is a narrow pass between two fortified ridges, both manned. You were watched from a distance of several miles before you reached this point. A gatekeeper with no visible weapons and too many rings checks your seal and your story. He does not tell you what happens to people whose stories do not hold up.",
      look: "Commoria's mountain pass entry. Two armed ridges, a ringworn gatekeeper, and a feeling of being assessed.",
      glance: "Commoria's mountain pass.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_nation_lemuria: {
      id: "arrive_nation_lemuria",
      name: "Lemuria — Eastern Harbor",
      description: "Lemuria's harbor is carved from natural rock, expanded over centuries into a sheltered anchorage for a hundred ships. The people here have golden eyes — not metaphorically, literally golden, irises the color of old coin. They are watching you with frank curiosity. Lemuria is not hostile. It is interested.",
      look: "Lemuria's eastern harbor. Rock-carved anchorage, golden-eyed people watching with open curiosity.",
      glance: "Lemuria's eastern harbor.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "civilized",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_nation_atlantis: {
      id: "arrive_nation_atlantis",
      name: "Atlantis — Blue Shore",
      description: "The Atlantean shore is blue stone and white sand, the water so clear you can see the bottom at depth. Behind the beach, the island rises in terraces of worked stone and crystal that have no business existing in the Thurian Age. Atlantis is the age of wonders in miniature — things here are older than the surface suggests, and stranger.",
      look: "Atlantis's blue shore. Crystal terraces rising behind white sand. The water is impossibly clear.",
      glance: "Atlantis's blue shore.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "civilized",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_geo_lost_lands: {
      id: "arrive_geo_lost_lands",
      name: "Lost Lands — Southern Fringe",
      description: "The road ends here, not at a gate or a marker but simply — the road stops, replaced by grass and old stone and the deep sound of something vast moving in the middle distance. The Lost Lands are lost for good reason. Eldar walk these territories, and dwarven stonework rises from the earth at intervals, and other things that predate both. You are the most temporary thing here.",
      look: "The Lost Lands fringe. The road simply stops. Something large moves in the middle distance.",
      glance: "The Lost Lands fringe.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_geo_worlds_end: {
      id: "arrive_geo_worlds_end",
      name: "World's End",
      description: "Past Stagus, the road simply stops. Not at a cliff, not at a sea — it stops at a line where the mapped world ends and whatever comes after begins. Beyond this point, no reliable reports exist. Those who have returned describe things that do not agree with each other. Those who have not returned are not available for comment.",
      look: "World's End. The road stops. Beyond, the world becomes something else. No map covers this.",
      glance: "World's End.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_nation_farsun: {
      id: "arrive_nation_farsun",
      name: "Farsun — Caravan Road",
      description: "Farsun is roads. Every road of consequence in the southern Thurian world passes through Farsun, and the Farsunians have built their kingdom around this fact. The entry is a caravan road wide enough for three wagons abreast, paved, clean, and lined with the guild-markers of a dozen trade organizations. Farsun welcomes travelers. It charges for the welcome.",
      look: "Farsun's caravan road. Wide-paved, guild-marked, busy with traders. Farsun charges for its welcome.",
      glance: "Farsun's caravan road entry.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "civilized",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_geo_red_isles: {
      id: "arrive_geo_red_isles",
      name: "Red Isles — Red Dock",
      description: "The Red Isles take their name from the stone — iron-rich, oxidized to a deep rust-red that stains the harbor water pink at low tide. The dock is rough timber and serious people who want to know why you have come. The mineral wealth here is real. So is the hostility to those who come to take it.",
      look: "The Red Isles dock. Red-stained stone, rough timber, and serious people asking why you are here.",
      glance: "Red Isles dock.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_geo_tathel_isle: {
      id: "arrive_geo_tathel_isle",
      name: "Tathel Isle — Anchor Bay",
      description: "Tathel Isle's anchor bay is sheltered by two arms of dark rock. The island is quiet in a way that is distinct from peaceful — a quiet of observation and isolation. The people here practice rites that predate the nations of the mainland. They receive visitors rarely and not always well.",
      look: "Tathel Isle's anchor bay. Dark rock, isolation, old rites. Visitors are received rarely.",
      glance: "Tathel Isle anchor bay.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_nation_kamelia: {
      id: "arrive_nation_kamelia",
      name: "Kamelia — Northern Gate",
      description: "Kamelia lies between Valusia and Thule, occupying the hill country around the Mirror valleys. Its northern gate is carved with the eye-sigil of Tuzun Thune — the kingdom's most famous and most dangerous landmark. Kamelians are careful, polite, and deeply suspicious of anyone who asks about the Mirrors.",
      look: "Kamelia's northern gate. The eye-sigil of Tuzun Thune carved in the stone. Polite, careful people.",
      glance: "Kamelia's northern gate.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "civilized",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_geo_mu: {
      id: "arrive_geo_mu",
      name: "Mu — Ruin Shore",
      description: "Mu should not exist. The legends say it sank. The ruin shore you stand on suggests the legends were premature — or that what sank and what remains are two different things, and only the wrong half went down. Ancient structures protrude from the waterline, carved in script no living scholar reads. The sea around the shore is warm and wrong.",
      look: "Mu's ruin shore. Ancient structures half-submerged. Warm sea. Unreadable script. Mu should not be here.",
      glance: "Mu's ruin shore.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_nation_thurania: {
      id: "arrive_nation_thurania",
      name: "Thurania — Stone Road",
      description: "Thurania's stone road runs south from the Valusian border through rolling hill country marked with burial mounds and standing stones. The Thuranians practice shamanic rites older than their kingdom and take their road maintenance very seriously. The two facts are not unrelated.",
      look: "Thurania's stone road. Burial mounds, standing stones, well-maintained road. Shamanic territory.",
      glance: "Thurania's stone road entry.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "civilized",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_geo_camoonian_desert: {
      id: "arrive_geo_camoonian_desert",
      name: "Camoonian Desert — Sand Road",
      description: "The Camoonian Desert begins without ceremony — the grass simply ends, and the sand begins. The sand road here is marked with stone cairns spaced half a day's ride apart. Between cairns, there is nothing but sand, heat, and the occasional ruin half-buried by centuries of drift. Carry water. There is none here.",
      look: "Camoonian Desert. The grass ends. Sand, cairns, ruined burial structures. No water.",
      glance: "Camoonian Desert entry.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_geo_zalgara_mts: {
      id: "arrive_geo_zalgara_mts",
      name: "Zalgara Mountains — Lower Pass",
      description: "The Zalgara Mountains are the great central spine of the known world, and the lower pass makes no pretense of being welcoming. The trail is stone switchbacks up loose scree, the wind is constant, and the summit is almost always in cloud. The Skull of Silence is somewhere above you to the north.",
      look: "The Zalgara Mountains lower pass. Loose scree, constant wind, cloud-covered summit. The Skull is above.",
      glance: "Zalgara Mountains lower pass.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "day",
    },
    arrive_geo_jungles: {
      id: "arrive_geo_jungles",
      name: "Thurian Deep Jungle — Trail's End",
      description: "The trail into the deep jungle ends when the canopy closes completely and the light goes green and flat. This is Serpent-Man territory — their temple complexes are hidden in the vine-choked ruins of something older than Valusia, older than the nations, older than the road you walked in on. You are being watched. You have been watched since you entered the jungle fringe.",
      look: "The Deep Jungle trail's end. Closed canopy, green light, Serpent-Man territory. You are being watched.",
      glance: "Deep Jungle trail's end.",
      exits: {},
      ...STUB_EMPTY,
      sceneTone: "grimdark",
      outdoor: true,
      timeOfDay: "day",
    },
  },
};
