// ============================================================
// Creator Forge — module list landing page (Sprint CF-0).
//
// Gated to roles creator | admin (see proxy.ts). Lives outside
// /admin/ so the URL reflects who's allowed there. Empty-state
// shell now; CF-1 wires the "New Module" wizard and CF-2+ surface
// per-module editors. Listing pulls from /api/creator/modules
// which reads module manifests from Supabase Storage.
// ============================================================

'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

interface ModuleListing {
  id: string;
  name: string;
  updatedAt: string;
}

export default function CreatorForgePage() {
  const [modules, setModules] = useState<ModuleListing[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/creator/modules')
      .then((r) => r.json())
      .then((data) => {
        if (!data.ok) {
          setError(data.error ?? 'failed to load modules');
          return;
        }
        setModules(data.modules ?? []);
      })
      .catch((err: unknown) => setError((err as Error).message));
  }, []);

  return (
    <div className="min-h-screen bg-slate-900 p-8">
      <div className="max-w-6xl mx-auto">
        <header className="mb-10">
          <p className="text-slate-500 text-sm">
            <Link href="/library" className="hover:text-white">← Library</Link>
          </p>
          <h1 className="text-4xl font-bold text-white mb-2 mt-2">
            Creator Forge
          </h1>
          <p className="text-slate-400 text-lg">
            Author adventure modules: rooms, atoms, NPCs, henchmen, art, narrative
            prose, Eamon-style map. Text generated by Claude Opus 4.7; images by
            Grok-Imagine-Pro.
          </p>
        </header>

        <section className="mb-8">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-2xl font-bold text-white">Modules</h2>
            <Link
              href="/creator-forge/new"
              className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded font-medium"
            >
              + New Module
            </Link>
          </div>

          {error && (
            <div className="bg-red-950 border border-red-800 rounded p-4 text-red-300">
              {error}
            </div>
          )}

          {!error && modules === null && (
            <div className="text-slate-500 italic">Loading…</div>
          )}

          {!error && modules !== null && modules.length === 0 && (
            <div className="bg-slate-800 border border-slate-700 rounded-lg p-10 text-center">
              <p className="text-slate-300 text-lg mb-2">No modules yet.</p>
              <p className="text-slate-500 text-sm">
                The wizard ships in Sprint CF-1. For now, the New Module button is
                a placeholder.
              </p>
            </div>
          )}

          {!error && modules !== null && modules.length > 0 && (
            <div className="grid gap-3">
              {modules.map((m) => (
                <Link
                  key={m.id}
                  href={`/creator-forge/${m.id}`}
                  className="block bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-lg p-5"
                >
                  <div className="text-white text-lg font-medium">{m.name}</div>
                  <div className="text-slate-500 text-xs mt-1">
                    <code>{m.id}</code> · updated{' '}
                    {new Date(m.updatedAt).toLocaleString()}
                  </div>
                </Link>
              ))}
            </div>
          )}
        </section>

        <footer className="mt-12 text-slate-500 text-sm">
          Draft modules persist in Supabase Storage (bucket{' '}
          <code>creator-modules</code>) until promoted. See{' '}
          <code>docs/plans/creator-forge-and-quest-line-orchestrator.md</code>.
        </footer>
      </div>
    </div>
  );
}
