// ============================================================
// Work-queue triager
//
// Walks EDGE_VECTORS.md + LAUNCH_CRITERIA.md and classifies every
// outstanding item into one of:
//   - awaits_answer    (open EV — needs Scotch's answer)
//   - awaits_approval  (launch-criteria gate with a textual blocker
//                       like "KARMA_SYSTEM.md §6 approval")
//   - ready_to_code    (launch item with no blockers, or upstream-id
//                       blockers whose targets are all shipped)
//   - blocked          (launch item with upstream-id blockers still
//                       not-shipped)
//   - done             (launch item: shipped)
//
// Emits:
//   - docs/work-queue.json (machine-readable; consumed by the
//     interviewer daemon's awaits_answer filter)
//   - docs/work-queue.md   (human/Claude-readable digest)
//
// Run:
//   npm run work-queue:build
//   (or: npx tsx scripts/build-work-queue.ts)
// ============================================================

import fs from "node:fs";
import path from "node:path";
import { loadEdgeVectors, type EdgeVectorEntry } from "../lib/library/edgeVectors";
import {
  loadLaunchItems,
  type LaunchItem,
  type LaunchStatus,
} from "../lib/library/launchCriteria";

const REPO_ROOT = process.cwd();
const OUT_JSON = path.join(REPO_ROOT, "docs", "work-queue.json");
const OUT_MD = path.join(REPO_ROOT, "docs", "work-queue.md");

// ── Schema (exported for the interviewer) ─────────────────────

export type WorkStatus =
  | "awaits_answer"
  | "awaits_approval"
  | "ready_to_code"
  | "blocked"
  | "done";

export interface WorkItem {
  id: string;
  kind: "ev" | "launch";
  status: WorkStatus;
  source_doc: string;
  category: string;
  priority: number;
  question?: string;
  best_guess?: string;
  blockers?: string[];
  resolution_path?: string;
  title?: string;
  good_looks_like?: string;
}

export interface WorkQueue {
  generated_at: string;
  stats: Record<WorkStatus, number>;
  items: WorkItem[];
}

// ── Classification ────────────────────────────────────────────

/**
 * A blocker token is "approval-text" if it doesn't match any launch
 * item id (i.e., it reads as prose like "MODULE_SYSTEM.md Stage I
 * approval"). This is the heuristic that distinguishes awaits_approval
 * (textual gate) from blocked (upstream-id gate).
 */
function classifyLaunch(item: LaunchItem, byId: Map<string, LaunchItem>): WorkStatus {
  if (item.status === "shipped") return "done";
  if (item.status === "deferred") return "done"; // off critical path

  const blockers = item.blockers ?? [];
  if (blockers.length === 0) return "ready_to_code";

  let hasUpstreamUnshipped = false;
  let hasApprovalText = false;
  for (const b of blockers) {
    const upstream = byId.get(b);
    if (upstream) {
      if (upstream.status !== "shipped") hasUpstreamUnshipped = true;
    } else {
      hasApprovalText = true;
    }
  }

  if (hasApprovalText) return "awaits_approval";
  if (hasUpstreamUnshipped) return "blocked";
  return "ready_to_code";
}

function evToWorkItem(ev: EdgeVectorEntry): WorkItem {
  return {
    id: ev.id,
    kind: "ev",
    status: "awaits_answer",
    source_doc: ev.sourceDocId,
    category: ev.category,
    priority: ev.affects.length, // unblock-impact proxy
    question: ev.question,
    best_guess: ev.bestGuess,
    resolution_path: ev.resolutionPath,
  };
}

function launchToWorkItem(item: LaunchItem, status: WorkStatus): WorkItem {
  const tierWeight = 100 - item.tier * 10;
  const criticality = item.criticality_flag === "high" ? 20 : 0;
  return {
    id: item.id,
    kind: "launch",
    status,
    source_doc: item.source,
    category: `TIER-${item.tier}`,
    priority: tierWeight + criticality,
    blockers: item.blockers,
    title: item.title,
    good_looks_like: item.good_looks_like,
  };
}

// ── Render ────────────────────────────────────────────────────

function renderMd(queue: WorkQueue): string {
  const lines: string[] = [];
  lines.push(
    `<!-- AUTO-GENERATED by scripts/build-work-queue.ts. Do not hand-edit. Run: npm run work-queue:build -->`
  );
  lines.push("");
  lines.push(`# Work Queue`);
  lines.push("");
  lines.push(`Generated ${queue.generated_at}.`);
  lines.push("");
  lines.push(
    `Triaged backlog of every outstanding item across the canon. The interviewer daemon reads this file's \`awaits_answer\` items; the coder picks from \`ready_to_code\`.`
  );
  lines.push("");
  lines.push(`## Stats`);
  lines.push("");
  lines.push(`- **awaits_answer:** ${queue.stats.awaits_answer} (open Edge Vectors — interviewer's queue)`);
  lines.push(`- **awaits_approval:** ${queue.stats.awaits_approval} (textual gates — Scotch decides)`);
  lines.push(`- **ready_to_code:** ${queue.stats.ready_to_code} (coder's queue)`);
  lines.push(`- **blocked:** ${queue.stats.blocked} (waiting on upstream launch items)`);
  lines.push(`- **done:** ${queue.stats.done} (shipped or explicitly deferred)`);
  lines.push("");

  const groups: { title: string; status: WorkStatus }[] = [
    { title: "awaits_answer (interviewer's queue)", status: "awaits_answer" },
    { title: "awaits_approval (Scotch decides)", status: "awaits_approval" },
    { title: "ready_to_code (coder's queue)", status: "ready_to_code" },
    { title: "blocked (waiting on upstream)", status: "blocked" },
    { title: "done (shipped or deferred)", status: "done" },
  ];

  for (const g of groups) {
    const items = queue.items
      .filter((i) => i.status === g.status)
      .sort((a, b) => b.priority - a.priority || a.id.localeCompare(b.id));
    if (items.length === 0) continue;
    lines.push(`## ${g.title}`);
    lines.push("");
    for (const it of items) {
      const heading = it.kind === "ev" ? `${it.id} \`[${it.category}]\`` : `${it.id} — ${it.title ?? ""}`;
      lines.push(`### ${heading}  \`priority: ${it.priority}\``);
      lines.push("");
      lines.push(`- **kind:** ${it.kind}`);
      lines.push(`- **source:** ${it.source_doc}`);
      if (it.blockers && it.blockers.length > 0) {
        lines.push(`- **blockers:** ${it.blockers.join(", ")}`);
      }
      if (it.question) lines.push(`- **Q:** ${it.question}`);
      if (it.best_guess) lines.push(`- **Best guess:** ${it.best_guess}`);
      if (it.resolution_path) lines.push(`- **Resolution path:** ${it.resolution_path}`);
      if (it.good_looks_like) lines.push(`- **What good looks like:** ${it.good_looks_like}`);
      lines.push("");
    }
  }

  return lines.join("\n") + "\n";
}

// ── Main ──────────────────────────────────────────────────────

function main(): void {
  const evs = loadEdgeVectors();
  const launches = loadLaunchItems();
  const byId = new Map(launches.map((l) => [l.id, l]));

  const items: WorkItem[] = [];
  for (const ev of evs) items.push(evToWorkItem(ev));
  for (const l of launches) items.push(launchToWorkItem(l, classifyLaunch(l, byId)));

  // Stable sort: status group, then priority desc, then id asc
  const STATUS_ORDER: Record<WorkStatus, number> = {
    awaits_answer: 0,
    awaits_approval: 1,
    ready_to_code: 2,
    blocked: 3,
    done: 4,
  };
  items.sort((a, b) => {
    const sd = STATUS_ORDER[a.status] - STATUS_ORDER[b.status];
    if (sd !== 0) return sd;
    if (a.priority !== b.priority) return b.priority - a.priority;
    return a.id.localeCompare(b.id);
  });

  const stats: Record<WorkStatus, number> = {
    awaits_answer: 0,
    awaits_approval: 0,
    ready_to_code: 0,
    blocked: 0,
    done: 0,
  };
  for (const it of items) stats[it.status]++;

  const queue: WorkQueue = {
    generated_at: new Date().toISOString().slice(0, 10),
    stats,
    items,
  };

  fs.mkdirSync(path.dirname(OUT_JSON), { recursive: true });
  fs.writeFileSync(OUT_JSON, JSON.stringify(queue, null, 2) + "\n", "utf-8");
  fs.writeFileSync(OUT_MD, renderMd(queue), "utf-8");

  console.log(
    `[work-queue:build] ${items.length} items: ${stats.awaits_answer} awaits_answer · ${stats.awaits_approval} awaits_approval · ${stats.ready_to_code} ready_to_code · ${stats.blocked} blocked · ${stats.done} done -> ${path.relative(REPO_ROOT, OUT_JSON)}, ${path.relative(REPO_ROOT, OUT_MD)}`
  );
}

main();
