// ============================================================
// Room Graph Builder — generates Mermaid diagram of room connectivity
//
// Walks ALL_ROOMS from lib/adventures/registry and emits:
//   - docs/room-graph.mmd (Mermaid flowchart LR)
//   - docs/room-graph.svg (rendered diagram, requires mmdc CLI)
//
// Run:
//   npm run room-graph:build      (generates .mmd only)
//   npm run room-graph:build:svg  (generates .mmd then .svg via mmdc)
//
// Optionally filter to one module:
//   tsx scripts/build-room-graph.ts --module guild_hall
//
// Deterministic: sorted rooms, stable iteration. Read-only against
// the registry. Regenerates from canonical source.
// ============================================================

import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { ALL_ROOMS, getModules } from "../lib/adventures/registry";

const REPO_ROOT = process.cwd();
const OUT_MMD = path.join(REPO_ROOT, "docs", "room-graph.mmd");
const OUT_SVG = path.join(REPO_ROOT, "docs", "room-graph.svg");

// ── Parse CLI args ─────────────────────────────────────────────

interface Args {
  module?: string;
  svg: boolean;
}

function parseArgs(): Args {
  const args: Args = { svg: false };
  for (let i = 2; i < process.argv.length; i++) {
    const arg = process.argv[i];
    if (arg === "--module" && i + 1 < process.argv.length) {
      args.module = process.argv[++i];
    } else if (arg === "--svg") {
      args.svg = true;
    }
  }
  return args;
}

// ── Mermaid helpers ────────────────────────────────────────────

function mermaidId(raw: string): string {
  return raw.replace(/[^a-zA-Z0-9_]/g, "_");
}

function escapeLabel(s: string): string {
  return s.replace(/"/g, "&quot;").replace(/`/g, "");
}

// ── Classify rooms by module type ──────────────────────────────

function getModuleType(moduleId: string): "guild_hall" | "destination_stubs" | "quest" | "unknown" {
  if (moduleId === "guild_hall") return "guild_hall";
  if (moduleId === "destination_stubs") return "destination_stubs";
  if (moduleId.startsWith("quest_")) return "quest";
  return "unknown";
}

function getModuleColor(type: "guild_hall" | "destination_stubs" | "quest" | "unknown"): string {
  switch (type) {
    case "guild_hall": return "#86efac"; // green
    case "destination_stubs": return "#fbbf24"; // amber
    case "quest": return "#60a5fa"; // blue
    case "unknown": return "#d1d5db"; // gray
  }
}

// ── Main ───────────────────────────────────────────────────────

function main() {
  const args = parseArgs();

  // Build a room → moduleId map
  const modules = getModules();
  const roomToModule = new Map<string, string>();
  for (const mod of modules) {
    for (const roomId of Object.keys(mod.rooms)) {
      roomToModule.set(roomId, mod.id);
    }
  }

  // Filter rooms if --module specified
  let roomIds = Object.keys(ALL_ROOMS).sort();
  let allRoomCount = roomIds.length;
  if (args.module) {
    roomIds = roomIds.filter((rid) => roomToModule.get(rid) === args.module);
  }

  // Build edges
  const edges: Array<{ from: string; to: string; direction: string }> = [];
  const roomsWithExits = new Set<string>();
  for (const roomId of roomIds) {
    const room = ALL_ROOMS[roomId];
    if (!room) continue;
    const exits = room.exits ?? {};
    for (const direction of Object.keys(exits)) {
      const targetRoomId = exits[direction];
      if (!targetRoomId) continue;
      // Only render edge if target is in our filtered set (or if no filter)
      if (args.module && !roomIds.includes(targetRoomId)) continue;
      edges.push({ from: roomId, to: targetRoomId, direction });
      roomsWithExits.add(roomId);
    }
  }

  // Build Mermaid
  const lines: string[] = [];
  lines.push("%% AUTO-GENERATED by scripts/build-room-graph.ts. Do not hand-edit.");
  lines.push("%% Run: npm run room-graph:build:svg");
  lines.push(`%% ${roomIds.length}/${allRoomCount} rooms`);
  lines.push("");
  lines.push("flowchart LR");
  lines.push("");

  // Group rooms by module id for subgraphs
  const roomsByModule = new Map<string, string[]>();
  for (const roomId of roomIds) {
    const modId = roomToModule.get(roomId) ?? "unknown";
    if (!roomsByModule.has(modId)) roomsByModule.set(modId, []);
    roomsByModule.get(modId)!.push(roomId);
  }

  // Emit subgraphs + room nodes
  for (const modId of Array.from(roomsByModule.keys()).sort()) {
    const rids = roomsByModule.get(modId)!.sort();
    const modType = getModuleType(modId);
    const safeModId = mermaidId(modId);

    lines.push(`  subgraph ${safeModId}["${escapeLabel(modId)} (${modType})"]`);
    lines.push("    direction TB");

    for (const roomId of rids) {
      const room = ALL_ROOMS[roomId];
      if (!room) continue;
      const nid = mermaidId(roomId);
      const label = escapeLabel(room.name || roomId);
      lines.push(`    ${nid}["${label}"]`);
    }
    lines.push("  end");
    lines.push("");
  }

  // Emit edges (inter-subgraph)
  if (edges.length > 0) {
    lines.push("  %% Connectivity");
    for (const edge of edges) {
      const fromId = mermaidId(edge.from);
      const toId = mermaidId(edge.to);
      const dirLabel = escapeLabel(edge.direction);
      lines.push(`  ${fromId} --> |"${dirLabel}"| ${toId}`);
    }
    lines.push("");
  }

  // Styling by module type
  lines.push("  %% Styling");
  lines.push(`  classDef guild_hall fill:#86efac,stroke:#16a34a,stroke-width:2px`);
  lines.push(`  classDef destination_stubs fill:#fbbf24,stroke:#d97706,stroke-width:2px`);
  lines.push(`  classDef quest fill:#60a5fa,stroke:#2563eb,stroke-width:2px`);
  lines.push(`  classDef unknown fill:#d1d5db,stroke:#6b7280,stroke-width:1px`);
  lines.push("");

  // Apply classes
  for (const modId of Array.from(roomsByModule.keys()).sort()) {
    const rids = roomsByModule.get(modId)!;
    const modType = getModuleType(modId);
    const nids = rids.map(mermaidId).join(",");
    if (nids) {
      lines.push(`  class ${nids} ${modType}`);
    }
  }

  const mermaidText = lines.join("\n") + "\n";

  // Write .mmd
  fs.mkdirSync(path.dirname(OUT_MMD), { recursive: true });
  fs.writeFileSync(OUT_MMD, mermaidText, "utf-8");

  const roomCount = roomIds.length;
  const edgeCount = edges.length;
  const moduleCount = roomsByModule.size;
  console.log(
    `[room-graph] ${roomCount} rooms · ${edgeCount} edges · ${moduleCount} modules → ${path.relative(REPO_ROOT, OUT_MMD)}`
  );

  // Optionally generate SVG
  if (args.svg) {
    try {
      execSync(`npx -y -p @mermaid-js/mermaid-cli@latest mmdc -i ${OUT_MMD} -o ${OUT_SVG}`, {
        stdio: "inherit",
      });
      console.log(`[room-graph] SVG generated → ${path.relative(REPO_ROOT, OUT_SVG)}`);
    } catch (err) {
      console.error(`[room-graph] mmdc failed (is @mermaid-js/mermaid-cli@latest available?)`);
      process.exit(1);
    }
  }
}

main();
