// ============================================================
// Sprint G2 -- Launch Readiness Report
//
// Reads docs/doc-graph.json + LAUNCH_CRITERIA.md, computes priority
// scores per launch item (with downstream EV + sprint-dependency
// signal), and emits docs/launch-readiness.md as a prioritized
// "what to authorize next" list.
//
// Run:
//   npm run launch:status
//   (or: npx tsx scripts/launch-readiness.ts)
//
// Priority formula:
//   priority = tier_weight + downstream_evs * 2 + downstream_sprints
//              + criticality_flag
//   where tier_weight = 100 - tier * 10
//         downstream_evs = count of EVs whose affects/source touches
//                          this item's affects_docs
//         downstream_sprints = count of OTHER launch items that name
//                              this item as a blocker
//         criticality_flag = +20 if hand-tagged "criticality_flag: high"
// ============================================================

import fs from "node:fs";
import path from "node:path";
import {
  loadLaunchItems,
  isActive,
  type LaunchItem,
  type LaunchStatus as Status,
} from "../lib/library/launchCriteria";

const REPO_ROOT = process.cwd();
const GRAPH_PATH = path.join(REPO_ROOT, "docs", "doc-graph.json");
const OUT_PATH = path.join(REPO_ROOT, "docs", "launch-readiness.md");

// ── Types ──────────────────────────────────────────────────────

interface ScoredItem extends LaunchItem {
  priority: number;
  downstream_evs: string[];
  downstream_sprints: string[];
}

// ── Parsers ────────────────────────────────────────────────────

interface GraphNode {
  type: string;
  id: string;
  source_doc?: string;
}

interface GraphEdge {
  from: string;
  to: string;
  type: string;
}

interface GraphPayload {
  generated_at: string;
  stats: { doc_count: number; ev_count: number; edge_count: number };
  nodes: Record<string, GraphNode & Record<string, unknown>>;
  edges: GraphEdge[];
}

function loadGraph(): GraphPayload {
  if (!fs.existsSync(GRAPH_PATH)) {
    throw new Error(
      `${GRAPH_PATH} missing. Run \`npm run graph:build\` first.`
    );
  }
  return JSON.parse(fs.readFileSync(GRAPH_PATH, "utf-8")) as GraphPayload;
}

// ── Scoring ────────────────────────────────────────────────────

function scoreItems(items: LaunchItem[], graph: GraphPayload): ScoredItem[] {
  // Build EV index: ev_id -> source_doc + affects[]
  const evIndex = new Map<
    string,
    { source: string; affects: string[] }
  >();
  for (const node of Object.values(graph.nodes)) {
    if (node.type !== "edge_vector") continue;
    const evId = node.id;
    const source = (node.source_doc as string) ?? "";
    const affects = graph.edges
      .filter(
        (e) => e.from === `ev:${evId}` && e.type === "affects" && e.to.startsWith("doc:")
      )
      .map((e) => e.to.replace(/^doc:/, ""));
    evIndex.set(evId, { source, affects });
  }

  // For each item, count downstream EVs (whose source/affects intersects
  // this item's affects_docs) and downstream sprints (other items naming
  // this as a blocker).
  return items.map((item) => {
    const itemDocs = new Set([
      item.id,
      ...(item.affects_docs ?? []),
    ]);

    const downstreamEvs: string[] = [];
    for (const [evId, { source, affects }] of evIndex.entries()) {
      const touches =
        itemDocs.has(source) || affects.some((d) => itemDocs.has(d));
      if (touches) downstreamEvs.push(evId);
    }

    const downstreamSprints = items
      .filter((other) => other.id !== item.id && (other.blockers ?? []).includes(item.id))
      .map((other) => other.id);

    const tier_weight = 100 - item.tier * 10;
    const criticalityBonus = item.criticality_flag === "high" ? 20 : 0;

    const priority =
      tier_weight + downstreamEvs.length * 2 + downstreamSprints.length + criticalityBonus;

    return {
      ...item,
      priority,
      downstream_evs: downstreamEvs.sort(),
      downstream_sprints: downstreamSprints.sort(),
    };
  });
}

// ── Render ─────────────────────────────────────────────────────

function render(scored: ScoredItem[], graph: GraphPayload): string {
  const lines: string[] = [];
  lines.push(
    `<!-- AUTO-GENERATED by scripts/launch-readiness.ts. Do not hand-edit. Run: npm run launch:status -->`
  );
  lines.push("");
  lines.push(`# Launch Readiness Report`);
  lines.push("");
  lines.push(`Generated ${graph.generated_at}.`);
  lines.push("");

  const active = scored.filter(isActive);
  const tier0Active = active.filter((s) => s.tier === 0);
  const tier1Active = active.filter((s) => s.tier === 1);
  const tier2Active = active.filter((s) => s.tier === 2);
  const shipped = scored.filter((s) => s.status === "shipped");
  const deferred = scored.filter((s) => s.status === "deferred");

  // Headline summary
  lines.push(`## Headline`);
  lines.push("");
  lines.push(
    `- **Tier 0 (MVP-blockers):** ${tier0Active.length} active · ${shipped.filter((s) => s.tier === 0).length} shipped`
  );
  lines.push(
    `- **Tier 1 (launch polish):** ${tier1Active.length} active · ${shipped.filter((s) => s.tier === 1).length} shipped`
  );
  lines.push(
    `- **Tier 2 (post-launch):** ${tier2Active.length} active · ${shipped.filter((s) => s.tier === 2).length} shipped · ${deferred.length} deferred`
  );
  lines.push(`- **Open Edge Vectors:** ${graph.stats.ev_count}`);
  lines.push("");

  // Critical-path bottleneck
  const top = [...tier0Active].sort((a, b) => b.priority - a.priority)[0];
  if (top) {
    lines.push(
      `> **Critical path:** [\`${top.id}\`](#${top.id}) — priority **${top.priority}** — ${top.downstream_sprints.length} downstream sprint(s) depend on this; ${top.downstream_evs.length} EV(s) blocked.`
    );
    lines.push("");
  }

  // Tier sections
  for (const [tierName, list] of [
    ["Tier 0 — MVP blockers", tier0Active],
    ["Tier 1 — Launch polish", tier1Active],
    ["Tier 2 — Post-launch", tier2Active],
  ] as const) {
    if (list.length === 0) {
      lines.push(`## ${tierName}`);
      lines.push("");
      lines.push(`*All items shipped or deferred.*`);
      lines.push("");
      continue;
    }
    lines.push(`## ${tierName}`);
    lines.push("");
    const sorted = [...list].sort((a, b) => b.priority - a.priority || a.id.localeCompare(b.id));
    for (let i = 0; i < sorted.length; i++) {
      const s = sorted[i];
      lines.push(`### ${i + 1}. <a id="${s.id}"></a>${s.title}  \`priority: ${s.priority}\``);
      lines.push("");
      lines.push(`- **Status:** ${s.status}`);
      lines.push(`- **Source:** ${s.source}`);
      if (s.blockers.length > 0)
        lines.push(`- **Blockers:** ${s.blockers.join(", ")}`);
      if (s.downstream_sprints.length > 0)
        lines.push(`- **Blocks (other launch items):** ${s.downstream_sprints.join(", ")}`);
      if (s.downstream_evs.length > 0)
        lines.push(`- **Blocks (open EVs):** ${s.downstream_evs.join(", ")}`);
      if (s.good_looks_like) lines.push(`- **What good looks like:** ${s.good_looks_like}`);
      lines.push("");
    }
  }

  // Shipped (Tier 0 + Tier 1)
  if (shipped.length > 0) {
    lines.push(`## Shipped`);
    lines.push("");
    const shippedTier0 = shipped.filter((s) => s.tier === 0).sort((a, b) => a.id.localeCompare(b.id));
    const shippedTier1 = shipped.filter((s) => s.tier === 1).sort((a, b) => a.id.localeCompare(b.id));
    if (shippedTier0.length > 0) {
      lines.push(`### Tier 0`);
      lines.push("");
      for (const s of shippedTier0) lines.push(`- ✅ **${s.title}** — ${s.source}`);
      lines.push("");
    }
    if (shippedTier1.length > 0) {
      lines.push(`### Tier 1`);
      lines.push("");
      for (const s of shippedTier1) lines.push(`- ✅ **${s.title}** — ${s.source}`);
      lines.push("");
    }
  }

  // Deferred
  if (deferred.length > 0) {
    lines.push(`## Explicitly deferred (post-launch)`);
    lines.push("");
    for (const s of deferred.sort((a, b) => a.id.localeCompare(b.id))) {
      lines.push(`- ⏸ **${s.title}** — ${s.source}`);
    }
    lines.push("");
  }

  // Method note
  lines.push(`---`);
  lines.push("");
  lines.push(
    `*Priority formula: \`tier_weight + downstream_evs × 2 + downstream_sprints + criticality_flag\`. Source: \`scripts/launch-readiness.ts\`. Run \`npm run launch:status\` to regenerate.*`
  );

  return lines.join("\n") + "\n";
}

// ── Main ───────────────────────────────────────────────────────

function main() {
  const graph = loadGraph();
  const items = loadLaunchItems();
  const scored = scoreItems(items, graph);
  const md = render(scored, graph);
  fs.writeFileSync(OUT_PATH, md, "utf-8");

  // Headline log
  const tier0Active = scored.filter((s) => s.tier === 0 && isActive(s));
  const top = [...tier0Active].sort((a, b) => b.priority - a.priority)[0];
  console.log(
    `[launch:status] ${items.length} items scored · ${tier0Active.length} Tier-0 active · top priority: ${
      top ? `${top.id} (${top.priority})` : "(none active)"
    } -> ${path.relative(REPO_ROOT, OUT_PATH)}`
  );
}

main();
