// ============================================================
// /admin/room-map — Room connectivity diagram (dev-only)
//
// Renders the Mermaid flowchart SVG generated by build-room-graph.ts
// ============================================================

import fs from "node:fs";
import path from "node:path";

export default function RoomMapPage() {
  const svgPath = path.join(process.cwd(), "docs", "room-graph.svg");
  let svgContent = "";
  let generated = "";

  try {
    svgContent = fs.readFileSync(svgPath, "utf-8");
    const stats = fs.statSync(svgPath);
    generated = new Date(stats.mtime).toISOString().split("T")[0];
  } catch (err) {
    return (
      <div className="p-8">
        <h1 className="text-2xl font-bold mb-4">Room Map</h1>
        <p className="text-red-600">
          SVG not found. Run <code className="bg-gray-100 px-2 py-1">npm run room-graph:build:svg</code>
        </p>
      </div>
    );
  }

  return (
    <div className="p-8">
      <h1 className="text-2xl font-bold mb-2">Room Map</h1>
      <p className="text-sm text-gray-600 mb-6">Generated {generated}</p>
      <div className="border border-gray-300 rounded bg-white overflow-auto">
        <div dangerouslySetInnerHTML={{ __html: svgContent }} />
      </div>
    </div>
  );
}
