"use client";

import type { SpriteMetadata } from "@/lib/art/spriteMetadata";

interface Props {
  metadata: SpriteMetadata;
  onCopy: () => void;
}

export default function PromptPanel({ metadata, onCopy }: Props): React.JSX.Element {
  const prompt = metadata.originalPrompt;
  return (
    <div style={panelStyle}>
      <div style={headerStyle}>
        <span>Original Prompt</span>
        {prompt && (
          <button
            onClick={onCopy}
            style={{
              padding: "2px 8px",
              background: "#333",
              color: "#eee",
              border: "1px solid #555",
              cursor: "pointer",
              fontSize: 11,
            }}
          >
            Copy
          </button>
        )}
      </div>
      {prompt ? (
        <pre style={preStyle}>{prompt}</pre>
      ) : (
        <div style={{ color: "#888", fontSize: 11, fontStyle: "italic", padding: 8 }}>
          No captured prompt — sprite predates Stage E prompt-capture, or was generated by a forge script that has not been wired up yet.
        </div>
      )}
      {metadata.promptRulesSnapshotId && (
        <div style={{ color: "#666", fontSize: 10, padding: "4px 8px" }}>
          rules snapshot: {metadata.promptRulesSnapshotId}
        </div>
      )}
    </div>
  );
}

const panelStyle: React.CSSProperties = {
  background: "#1a1a1a",
  border: "1px solid #333",
};

const headerStyle: React.CSSProperties = {
  padding: "6px 10px",
  background: "#222",
  color: "#eee",
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  fontSize: 12,
};

const preStyle: React.CSSProperties = {
  margin: 0,
  padding: 8,
  fontSize: 10,
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
  color: "#ccc",
  whiteSpace: "pre-wrap",
  wordBreak: "break-word",
  maxHeight: 240,
  overflowY: "auto",
};
