-- Character Creation — Sprint 2a
-- hero_masters: the library of hero appearance masters (curated + player-forged).
-- players links to its chosen master via hero_master_id.

create table if not exists public.hero_masters (
  id uuid primary key,

  -- Human-readable handle. Unique for curated entries; uniqueness not enforced
  -- across player-forged entries (different players may forge a hero they call
  -- "Kane" with different faces).
  slug text not null,

  -- Suggested name. Shown in the wizard; the player may override it.
  hero_name text not null,

  -- The full customization vector used to generate the master. jsonb keeps
  -- schema-flexible and lets us evolve HeroCustomization without migrations.
  customization_vector jsonb not null,

  -- The EXACT Identity Block text fed to Grok Imagine at master-generation
  -- time. Re-sent verbatim (alongside the master image as reference) on every
  -- future scene-image call for this hero. This is the coherence lock.
  identity_block text not null,

  -- Public URL to the transparent-PNG master in Supabase Storage.
  master_image_url text not null,

  -- 'curated' = pre-approved library entries Scotch forged.
  -- 'player_forged' = generated by a player via the opt-in Forge path (v1.1+).
  source text not null default 'curated'
    check (source in ('curated', 'player_forged')),

  -- For player-forged masters: who made them. Null for curated.
  creator_player_id uuid references public.players(id) on delete set null,

  -- If a player forged this hero, do they consent to share it with others in
  -- the library? Defaults true for curated. Opt-in / -out for player-forged.
  consent_shared boolean not null default true,

  -- How many heroes have chosen this master. Informational.
  times_chosen integer not null default 0,

  approved_at timestamptz not null default now(),
  retired_at timestamptz
);

-- Fast fetch of the live curated library.
create index if not exists hero_masters_source_live_idx
  on public.hero_masters(source)
  where retired_at is null;

-- For future: look up a player's own forged heroes.
create index if not exists hero_masters_creator_idx
  on public.hero_masters(creator_player_id)
  where creator_player_id is not null;

-- Link from a player to their chosen appearance.
alter table public.players
  add column if not exists hero_master_id uuid
    references public.hero_masters(id) on delete set null;

-- Optional short backstory the player writes in the wizard.
alter table public.players
  add column if not exists backstory text;
